### ISSUE TITLE
Nosso numero no retorno do Sicoob parece não estar certo

### ISSUE THREAD

**Issue by marceloboth** [kivanio/brcobranca#102]
Quando ocorre a leitura do nosso número no retorno Cnab 240 do Sicoob, pelo que constatei o valor recuperado está incorreto. No caso a leitura é feita entre os campos caracteres 46 e 56, no entanto na documentação é especificado da seguinte forma:
Seq: 13.3T
Posição: 38 a 57
Nosso Número:
- Se emissão a cargo do Sicoob (vide planilha "Capa" deste arquivo): Brancos
- Se emissão a cargo do Beneficiário (vide planilha "Capa" deste arquivo):
     NumTitulo - 10 posições (1 a 10) 
     Parcela - 02 posições (11 a 12) - "01" se parcela única
     Modalidade - 02 posições (13 a 14) - vide planilha "Capa" deste arquivo
     Tipo Formulário - 01 posição  (15 a 15):
          "1" -auto-copiativo
          "3"-auto-envelopável
          "4"-A4 sem envelopamento
          "6"-A4 sem envelopamento 3 vias
     Em branco - 05 posições (16 a 20)

Ou seja, numa linha como: 
`7560001300001T 0603032000000004587160000000008301011 ...`, o valor extraído é `301011` ao invés de `0000000083`.

No caso estou disposto a implementar a correção, caso essa minha analise estiver correta.

**Comment by Gubio** [comment]
acabei de ler a documentação do retorno Cnab 240 do Sicoob e você está correto em sua analise.

**Comment by kivanio** [comment]
A parte que realmente interesa é somente a:
NumTitulo - 10 posições (1 a 10)

A parcela e o resto não fazem parte do nosso número real do boleto.
Esse boleto é o 83.

Quando for gerar o boleto, você informar qual é o número dele, 10, 20, 40,
e é esse número que você deve pegar do arquivo depois para fazer
conferência.



Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by marceloboth** [comment]
Ok, vou criar uma classe especifica de retorno para o Sicoob e pegar esse NumTitulo.
