### ISSUE TITLE
App completo para geração de boletos

### ISSUE THREAD

**Issue by thiagoc7** [kivanio/brcobranca#103]
Caros,

implantei com sucesso o brcobrança em meu erp interno, e agora extrai a geração de boletos em um repo, https://github.com/thiagoc7/brcobranca_app

Caso interesse a alguém, está tudo pronto para gerar boletos, com cadastro de bancos e clientes.
A geração de boletos foi toda criada com react, é um "mini SPA".
Para nós ficou bem produtivo, inclusive cadastrando "on the fly" novos clientes.

Mais pra frete vou tentar deixar o app mais completo, com todos os bancos em um drop, um readme, etc.
Por enquanto está exatamente como eu uso, mas acho q já pode ajudar.

abs!

**Comment by kivanio** [comment]
@thiagoc7 vou colocar no README, blz?
