### ISSUE TITLE
Código da carteira na remessa do Banco do Brasil

### ISSUE THREAD

**Issue by marceloboth** [kivanio/brcobranca#104]
Estou usando as remessas do Brcobranca e percebi que na atualização para a versão 6.1.0, no segmento P digito 58, o valor está sendo sempre retornado como 7 no Banco do Brasil. Achei estranho pois esse campo é referente ao digito da carteira e mesmo quando eu informo carteiras 11, 12 o valor retornando é 7 ao invés de 1. Está correto dessa forma ou trata-se de algum bug?

**Comment by kivanio** [comment]
É só colocar o valor do codigo_carteira na inicialização conforme:
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/cnab240/banco_brasil.rb#L162
