### ISSUE TITLE
Alternar entre rghost e rghost_carne

### ISSUE THREAD

**Issue by brunorails** [kivanio/brcobranca#107]
É possível a mesma aplicação, hora imprimir usando o formato padrão e hora imprimir usando o rghost_carne ?

**Comment by kivanio** [comment]
Você teria que trocar o Brcobranca.configuration.gerador antes de criar o boleto.
Mas acho que não vai rolar legal.
Mas só testando e caso não der, precisa ver como mudar o código para permitir.

**Comment by brunorails** [comment]
É, eu tentei mudar dessa forma, mas parece que ele só pega a configuração na hora de iniciar a aplicação, depois não muda mais.

Então só funcionou sendo tudo carnê ou tudo no formato normal
