### ISSUE TITLE
Arquivo de retorno

### ISSUE THREAD

**Issue by ricardobsilva** [kivanio/brcobranca#112]
Pessoal, alguém tem um exemplo de baixa automática com arquivo de retorno?
Não encontrei nenhum exemplo.

**Comment by efmiglioranza** [comment]
O que você chama por baixa automática? Para processar arquivos de retorno eu faço assim:

```ruby
records = Brcobranca::Retorno::Cnab400::Base.load_lines(some_file_path)
records.each { |r| puts r.nosso_numero }
```

**Comment by ricardobsilva** [comment]
Exatamente isso. Valeu,cara.

**Comment by danieldenis01** [comment]
acho que você pode utilizar:
> Brcobranca::Retorno::Cnab240::Base.load_lines
