### ISSUE TITLE
Homologação Sicoob

### ISSUE THREAD

**Issue by brunofrank** [kivanio/brcobranca#116]
Prezados, estou fazendo a homologação do Sicoob em Goiás, eu acredito que seja igual em todo o brasil, porém me deparei com o seguinte problema, o calculo do DV do nosso número está incorreto, analisando não entendi alguns pontos:

Qual o motivo de reverter a ordem do nosso número antes de aplicar os multiplicadores?
```ruby
      to_s.split(//).reverse!.each do |caracter|
        total += (caracter.to_i * multiplicador).soma_digitos
        multiplicador = multiplicador == 2 ? 1 : 2
      end
```

Ao fazer o mapeamento ele deveria fazer sobre o resto e não sobre resultado?
```ruby
       valor = block_given? ? yield(total) : (total % 11)
      options[:mapeamento][valor] || valor
```

O número do convenio no calculo do DV deve ter 10 dígitos o nosso número 7!

Eu fiz a seguinte alteração e funcionou
calculo.rb
```ruby
      rest = (total % 11)
      valor = block_given? ? yield(total) : rest
      options[:mapeamento][rest] || valor
```
calculo.rb
```ruby
      to_s.split(//).each do |caracter|
        total += (caracter.to_i * multiplicador).soma_digitos
        multiplicador = multiplicador == 2 ? 1 : 2
      end
```
sicoob.rb
```ruby
      def nosso_numero_dv
        "#{agencia}#{convenio.rjust(10, "0")}#{numero_documento}".modulo11(
          multiplicador: [3, 1, 9, 7],
          mapeamento: { 0 => 0, 1 => 0, 10 => 0, 11 => 0 }
        ) { |t| 11 - (t % 11) }
      end
```
Será que só nesse banco é feito assim? 

Segue uma lista com números gerados pelo banco para comparação.
![screenshot 2015-12-16 19 10 07](https://cloud.githubusercontent.com/assets/40139/11854062/a875e052-a428-11e5-8884-989bcb8a5671.png)

**Comment by kivanio** [comment]
Esse banco já está homologado

**Comment by anylyne** [comment]
Boa Noite Kivanio, 

Tive problemas com a homologação do Boleto Sicoob DF. Gostaria de saber como faço para setar os  campos detalhados na imagem abaixo: 
![indi](https://cloud.githubusercontent.com/assets/35921/15488895/4665b082-2131-11e6-96a3-bcfc595b2e6c.png)

Desde já agradeço,

**Comment by kivanio** [comment]
Isso só enviando um path para o código pois é calculado automaticamente.

Qual formato usou, 400 ou 240?


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

On Mon, May 23, 2016 at 9:06 PM, Carol Mascarenhas <notifications@github.com

**Comment by anylyne** [comment]
Oi Kivanio, 
Muito obrigada pela resposta! Estou utilizando o 240.
Abraço, 
Carol.

**Comment by anylyne** [comment]
Oi Kivanio, 

O Patch que você mencionou é algo que você já tem implementado?

[],

**Comment by kivanio** [comment]
Não.

É preciso fazer enviar.

Testa com o de 400.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by anylyne** [comment]
Olá Kivanio,

Eu fiz a alteração em um branch meu e corrigi os testes relacionados ao
sicoob. E mandei o arquivo para pré-homologação.

https://github.com/kivanio/brcobranca/compare/master...anylyne:2016_05_24_totais_trailers_cnab240

A suite de testes ainda possui 8 testes falhando devido ao impacto. Mas
queria sua opinião... se você achar que o código está correto posso enviar
o pull request depois de dar uma olhadinha nesses testes que estão falhando.

Abraços,
Carol.


2016-05-25 15:06 GMT-03:00 Kivanio Barbosa <notifications@github.com>:

> Não.
>
> É preciso fazer enviar.
>
> Testa com o de 400.
>
> Kivanio Barbosa
> *boletosimples* Profissionalize sua cobrança com boleto bancário!
> BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
> <http://cobregratis.com.br/>
>
> On Tue, May 24, 2016 at 10:23 PM, Carol Mascarenhas <

**Comment by kivanio** [comment]
Então, não mude no Base.

Mude somente na classe do Sicoob, assim só os testes do sicoob precisarão
de correção.

Basta você sobrescrever esse monta_trailer_lote na classe do Sicoob.

Crie um monta_trailer_lote(nro_lote, nro_registros) no sicoob e faça os
ajustes nele.

Um exemplo para compreender é nos cnab 400.
Também tive que fazer uma correção no Santader e Sicoob, então sobreescrevi
o método neles:

Original:
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/cnab400/base.rb#L47

Formatado para cada banco:
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/cnab400/santander.rb#L190
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/cnab400/sicoob.rb#L281



Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2016-05-25 19:53 GMT-04:00 Carol Mascarenhas <notifications@github.com>:

> Olá Kivanio,
>
> Eu fiz a alteração em um branch meu e corrigi os testes relacionados ao
> sicoob. E mandei o arquivo para pré-homologação.
>
>
> https://github.com/kivanio/brcobranca/compare/master...anylyne:2016_05_24_totais_trailers_cnab240
>
> A suite de testes ainda possui 8 testes falhando devido ao impacto. Mas
> queria sua opinião... se você achar que o código está correto posso enviar
> o pull request depois de dar uma olhadinha nesses testes que estão
> falhando.
>
> Abraços,
> Carol.
>
>
> 2016-05-25 15:06 GMT-03:00 Kivanio Barbosa <notifications@github.com>:
>
> > Não.
> >
> > É preciso fazer enviar.
> >
> > Testa com o de 400.
> >
> > Kivanio Barbosa
> > *boletosimples* Profissionalize sua cobrança com boleto bancário!
> > BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
> > <http://cobregratis.com.br/>
> >
> > On Tue, May 24, 2016 at 10:23 PM, Carol Mascarenhas <
