### ISSUE TITLE
Número do documento

### ISSUE THREAD

**Issue by lincolnd** [kivanio/brcobranca#117]
Bom dia.

Analisando o código vi que o atributo nosso número é usado tanto no número bancário quanto no número do documento do boleto. Há alguma forma de personificar este número do documento tal qual está no manual?

Obrigado.

**Comment by kivanio** [comment]
Não.

Isso foi uma falha da primeira versão.
Se você quiser investir um tempo e separar os dois, fique a vontade.
Já faz um tempo que quero fazer isso, mas estou sem tempo.

É só enviar um pull request que ajudo no que der.

**Comment by lincolnd** [comment]
Beleza, Kivanio.

Vou ver aqui e conforme for, eu te comunico.

Obrigado.

**Comment by rvalyi** [comment]
esse issue parece ser solucionado por esse PR https://github.com/kivanio/brcobranca/pull/146
iremos confirmar em breve. cc @mbcosta @renatonlima

**Comment by mbcosta** [comment]
O problema foi corrigido no commit https://github.com/kivanio/brcobranca/commit/aa5f903fd27b7384fadc74951582f358da0fdcb3#diff-782276f626e10468be3c1cdcf257f087 , acredito que podem encerrar esse issue
