### ISSUE TITLE
Se UF do Pagamento for maior que 2 caracteres, quebra o arquivo de remessa

### ISSUE THREAD

**Issue by pedrobachiega** [kivanio/brcobranca#123]
Percebi durante uma homologação com o banco que, se enviar no campo `uf_sacado` do `Brcobranca::Remessa::Pagamento` alguma informação maior que 2 caracteres, ele gera o arquivo de remessa de forma errada, já que não limita esse campo para somente 2 caracteres.

Estou abrindo um Fork com PR para tal correção, mas gostaria de abrir pra discussão se é melhor usar uma validação, ou se é melhor simples cortar o texto.

O que acham?

**Comment by efmiglioranza** [comment]
Acredito que validação seja sempre melhor, falha silenciosa pode ser
perigosa.

Em 10 de maio de 2016 10:38, Pedro Bachiega <notifications@github.com>
escreveu:

**Comment by pedrobachiega** [comment]
Makes sense!
PR aberto.
