### ISSUE TITLE
Santander: Arquivo de remessa indo sem o dígito verificador do nosso número

### ISSUE THREAD

**Issue by pedrobachiega** [kivanio/brcobranca#125]
Pessoal,
pela homologação do Santander, eles informam que o dígito verificador do `nosso_numero` não está indo no arquivo de remessa, já que ele aparece no boleto.
Realmente não vai, porque [ele pega direto `pagamento.nosso_numero`](https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/cnab400/santander.rb#L96).

Vejo duas formas de resolver isso:
1) [extrair o cálculo do dígito verificador](https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/boleto/santander.rb#L46) e eu controlar na minha aplicação isso e setar na hora de usar o `pagamento.nosso_numero = ***`; ou
2) colocar isso direto na gema, para automaticamente inserir o digito verificador no arquivo de remessa.

O que acham?
Fazemos direto na gema? Possíveis problemas disso?

E já aproveitando, como vocês gerenciam o versionamento da gema?

**Comment by kivanio** [comment]
Só daria para fazer se fossem criados pagamentos por bancos:
SantanderPagamentos, BBPagamentos

e etc.

Isso porque cada banco aceita o nosso numero de um jeito diferente.

No meu caso, controlo na aplicação.

Quando você gera o boleto, você pega o nosso número usado no layout do
boleto e limpa ele:

boleto.nosso_numero_boleto.to_s.gsub(/\D/, ‘')

E fica resolvido de uma forma genérica.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2016-05-10 11:33 GMT-04:00 Pedro Bachiega <notifications@github.com>:

**Comment by pedrobachiega** [comment]
Obrigado pela resposta Kivanio!
Faz sentido e vou ver como controlar na minha aplicação então.

Aproveitando, algum motivo especial de existir o `Pagamento` ao invés de usar o `Boleto` diretamente para o arquivo de remessa?

Um abraço

**Comment by kivanio** [comment]
Primeiro porque não foi eu que fiz :D
Foi uma contribuição de usuário \o/

Depois, você notara que na remessa tem muito mais informação que em um
boleto.
Não dá para ser o mesmo objeto.


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2016-05-10 17:43 GMT-04:00 Pedro Bachiega <notifications@github.com>:
