### ISSUE TITLE
Boleto Caixa

### ISSUE THREAD

**Issue by romarioddo** [kivanio/brcobranca#135]
Estou utilizando a gem para a geração do boleto caixa e o processo de homologação não foi aprovado.

Segundo a Caixa: "Não constam nos boletos itens obrigatórios conforme MO67119"
Após uma pesquisa na internet encontrei a especificação dos boletos da Caixa

Link: http://www.caixa.gov.br/site/paginas/downloads.aspx/asp/ent_hist.asp
Ao pesquisar por SIGCB retornam 4 resultados:
- Manual_Leiaute_CNAB240_SIGCB.pdf
-     Manual_Leiaute_CNAB400_SIGCB.pdf
-     ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf
-     Cobranca_CAIXA.EXE

O MO67119 corresponde ao documento ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf

Os problemas relatados pelo processo de homologação com a Caixa foram os seguintes:

> 3.2 INFORMAÇÕES OBRIGATÓRIAS 
> - **Recibo do Pagador (expressão para identificação da via ou parte).**
> 
> **3.2.2 Se no Recibo do Pagador houver a impressão da logomarca CAIXA, é ainda obrigatório constar:
> SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogios)
> Para pessoas com deficiência auditiva ou de fala: 0800 726 2492
> Ouvidoria: 0800 725 7474
> caixa.gov.br**
>  
> 4.2.3.1 – BENEFICIÁRIO: 
> - **Nome: Razão Social ou Nome Fantasia do Beneficiário.**
> - **CPF/CNPJ**
> - **Endereço**
> 
> **Obs.: Caso o Endereço do Beneficiário não conste na Ficha de Compensação deve constar no Recibo do Pagador.**
>  
> **4.2.5.2 – CARTEIRA: 
> Informar SR para título da modalidade SEM REGISTRO ou RG para título da modalidade REGISTRADA.**

Alguém enfrentou problemas semelhantes?

**Comment by kivanio** [comment]
Up PR seria bom :D

Você tem a opção de dizer que entende, mas que quer que a carteira entre em
produção.
O gerente vai te dar um papel para assinar dizendo que você quis isso e o
processo segue normalmente.

Nenhuma dessas modificações implica no recebimento do boleto, é apenas
‘maquiagem’ que cada banco pede.

Essas informações também podem ser inseridas nos campos de instrução por
exemplo.
O endereço no endereço.


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2016-08-24 14:50 GMT-04:00 Romário De Oliveira <notifications@github.com>:

**Comment by romarioddo** [comment]
Vi que já houve uma tentativa (#122) de resolver esse problema com a carteira, então nada melhor do que corrigir para não precisar solicitar esse documento ao gerente.

Vou fazer um PR em breve sobre esse item da carteira. Assim que conseguirmos homologar.
Sobre os demais itens que são apenas 'maquiagem' vamos tentar conversar com o gerente e justificar que o boleto da gem já esta homologado e não haveria necessidade de tais mudanças.

Obrigado pelos esclarecimentos

**Comment by marceloboth** [comment]
@romarioddo vc conseguiu homologar essa carteira, não fazendo aqueles pedidos que a homologação fez e conversando com o banco para seguir com carteira mesmo sem essas maquiagens? Estou passando por esse mesmo problema, onde reprovaram a homologação pois não tem o bendito 0800. Mesmo informando no demonstrativo do boleto.

**Comment by romarioddo** [comment]
@marceloboth não estou mais trabalhando na empresa onde estava desenvolvendo esse projeto. Pelo que conversei com meus amigos que ainda trabalham lá o projeto esta engavetado, hehehehe.

Mas enquanto estava na empresa não tínhamos conseguido seguir adiante com a homologação devido aos itens descritos

**Comment by marceloboth** [comment]
Fiz as alterações pedidas pela caixa, e está em processo de homologação, assim que tiver a aprovação envio o PR com a alteração.
