### ISSUE TITLE
Ajuda com Arquivo de Retorno Sicoob

### ISSUE THREAD

**Issue by anylyne** [kivanio/brcobranca#137]
Olá Pessoal estou tendo problemas na leitura do Arquivo de Retorno SICOOB. A gem dá erro 

> ArgumentError (invalid byte sequence in UTF-8):

na linha 16 da classe Brcobranca::Retorno::Cnab240::Sicoob.rb

Alguém já teve este problema?

**Comment by efmiglioranza** [comment]
Olá Carol. Pela mensagem parece que há algum erro em ler o arquivo em
UTF-8. Você tem certeza que o arquivo de retorno está em UTF-8?

2016-09-09 11:33 GMT-03:00 Carol Mascarenhas <notifications@github.com>:

**Comment by anylyne** [comment]
Olá Ewerton, 

Muitíssimo obrigada pela sua resposta e desculpe ter demorado tanto para dar um retorno. 

O Sicoob está com problemas na geração dos arquivos pelo **Sicoobnet Empresarial**. Eles me indicaram baixar os arquivos de retorno pelo **Módulo Cedente** (essas são as 2 soluções do sicoob para upload da remessa e download do retorno). 

Mas no fim das contas recebi a seguinte informação do suporte deles: "O arquivo retorno é gerado no padrão ANSI e seu sistema deverá recebe-lo com ANSI." Será que ninguém teve este problema usando a gem br_cobranca?

Como será que podemos adaptar?

Att, 
Carol.

**Comment by efmiglioranza** [comment]
Olá Carol, imagina hehe. Dá uma olhada na biblioteca de encoding do Ruby
https://ruby-doc.org/core-2.2.0/Encoding.html

Por padrão, se não me engano, UTF-8 é compatível com ANSI, então o problema
pode ser também que você está lendo o arquivo fora dos limites dele ou da
linha. Se você colocar o código acho que fica mais fácil de ver. Abraço!

Em 20 de setembro de 2016 10:00, Carol Mascarenhas <notifications@github.com

**Comment by ronyvieira** [comment]
Boa tarde @anylyne,

Conseguiu resolver esse problema? Estou tentando importar um retorno enviado pelo Sicoob e infelizmente está vindo com essa sequência de caracteres inválidos.

**Comment by brunobrgs** [comment]
Eu também estou com o mesmo problema, na remessa eu mando o nome dos clientes sem nenhum acento, porém, no retorno, alguns nomes estão voltando acentuados (não sei como).
Então, sempre que tem algum acento no arquivo, ele da problema na leitura.

**Comment by ronyvieira** [comment]
@brunobrgs Não achei uma solução melhor do que a citei anteriormente... Ainda estou usando ela. 
```
      original_text = resource.tempfile.read
      utf8_encoded_text = original_text.encode("UTF-8", :invalid=>:replace, :undef => :replace, :replace=>"?").encode('UTF-8')

      new_file = Tempfile.new('retorno', :encoding => 'utf-8')
      new_file.write(utf8_encoded_text)
      new_file.close
```
