### ISSUE TITLE
Divergência no campo Aceite

### ISSUE THREAD

**Issue by ronyvieira** [kivanio/brcobranca#138]
Estava lendo a documentação dos bancos e reparei que o campo "Aceite" representa se o pagador tem conhecimento da dívida e tem valores possíveis de 'A' e 'N', porém no código está informando que é o campo que informa se o documento deve ser recebido após o vencimento e valores 'S' e 'N'.

Código Fonte:

> Informa se o banco deve aceitar o boleto após o vencimento ou não( S ou N, quase sempre S)

Documentação do Banco:

> Código adotado para identificar se o título de cobrança foi aceito (reconhecimento da dívida pelo
> Pagador).
> ‘A’ = Aceite
> ‘N’ = Não Aceite

Alguém sabe me informar se isso está certo ou se estou fazendo alguma confusão?

**Comment by kivanio** [comment]
Na verdade cada banco tem um formato.
S/N
A/N
e até
0/1

É preciso extrair um aceite para o pagamento,
dessa forma é possível enviar no parâmetro aceite o valor certo para cada banco.
Além de ser por banco, hoje está fixo para a remessa toda, o que é errado.
