### ISSUE TITLE
Remessa Sicredi

### ISSUE THREAD

**Issue by luizpicolo** [kivanio/brcobranca#143]
Iniciei implementação do modulo para a geração do arquivo de remessa para o banco Sicredi. Criei esta issues pois não sei se há alguém que tenha dado início a uma feature semelhante. 

- [x] Implementar modulo Cnab400 para banco Sicredi (iniciado);
- [ ] Implementar testes para o modulo criado;
- [ ] Homologar arquivo com o banco.

**Comment by marceloboth** [comment]
@luizpicolo implementei a remessa do Sicredi, mas para CNAB 240 e foi homologada. Na verdade tem mais umas remessas, retornos e boletos implementados (que estão em processo de homologação), que em breve quero mandar para cá. O problema que tive que adicionar mora, juros e multas na remessa, adicionando o segmento R, que vai me dar um pouco de trabalho para extrair e mandar um PR limpo para avaliação.

**Comment by kivanio** [comment]
@marceloboth manda o PR que ajudamos \o/

**Comment by luizpicolo** [comment]
Entendido @marceloboth e bom trabalho. 

Único problema até agora é entender a documentação do banco :smile:. Porém, acredito que até sexta tenha completado essa _feature_ e tentarei enviar para o banco semana que vem. 

Já o PR vai demorar um pouco mais, pois, como preciso dessa remessa para ontem, vou fazer Test After.

**Comment by efmiglioranza** [comment]
Olá @luizpicolo tudo bem? Tens alguma atualização sobre a remessa do Sicredi? Estou precisando também, se precisar de ajuda é só falar, abraço!

**Comment by luizpicolo** [comment]
Olá @efmiglioranza tudo tranquilo? Então, eu estava montando este arquivo de remessa e até tinha concluído e enviado para o banco para a homologação. Porém, não estou mais na empresa onde comecei o projeto, logo, não tenho mais os arquivos.
