### ISSUE TITLE
Boletos registrados

### ISSUE THREAD

**Issue by alexanmtz** [kivanio/brcobranca#147]
Como é feito a migração para boletos registrados? Tenho um cliente que usa a plataforma e não consegui encontrar aqui como foi feita esta migração e o que precisa ser feito. Como faço para o `brcobranca` emitir boletos registrados?

**Comment by marceloboth** [comment]
@alexanmtz seu cliente vai precisar ter com o banco uma carteira com registro. Com isso será necessário emitir o boleto com a carteira e enviar a remessa dos boletos gerados ao banco, para ocorrer o registro. Antes de iniciar em produção, os bancos orientam que mande boletos de exemplo (geralmente 10) e a remessa constando esse títulos para homologar.

**Comment by alexanmtz** [comment]
Brigado pela resposta @marceloboth e pelos esclarecimentos. Então eu não preciso fazer nada do lado do `brcobranca`? Se tiver no banco uma carteira com registro eu posso continuar usando a geração pelo `brcobranca`e enviá-las ao banco?

**Comment by marceloboth** [comment]
Vai ter que ver se no Brcobranca tem a geração de remessa para o banco que seu cliente está usando. Como falei, é necessário enviar a remessa com os dados do boletos gerados, para o banco registrar. Outro ponto, se o seu sistema controla todo o financeiro, e precisa atualizar seus registros com as ocorrências dos títulos no banco, vai precisar ter o processamento do retorno bancário. O fluxo nesse caso seria: Cria o boleto, envia a remessa para o banco e no dia seguinte processa o retorno para fazer a baixa, liquidação e os procedimentos que se depende do banco.

**Comment by alexanmtz** [comment]
Muito obrigado @marceloboth
