### ISSUE TITLE
É possivel emitir boletos registrados com esta gem?

### ISSUE THREAD

**Issue by ademir10** [kivanio/brcobranca#149]
Boa tarde! primeiramente gostaria de parabenizar á todos envolvidos neste projeto e dizer que esta gem ficou sensacional! Já instalei e fiz todas as customizações de acordo com as necessidades do meu projeto, porém fiquei com uma dúvida, me desculpem pela falta de entendimento no assunto, mais gostaria de saber se é possível emitir boletos registrados com esta mesma gem?

Se alguém puder explicar o que seria necessário caso haja a possibilidade eu ficaria inteiramente grato.
Obrigado.

**Comment by marceloboth** [comment]
@ademir10 sim é possível. Veja https://github.com/kivanio/brcobranca/issues/147

**Comment by ademir10** [comment]
muito obrigado pela resposta rápida @marceloboth !
pelo que você explicou, no meu caso seria só emitir os boletos normalmente e ai faltaria somente enviar as remessas para o banco, porque o processo de verificação dos pagamentos é feito um á um por se tratarem de clientes de pequeno porte. Seria só isso mesmo né? no meu caso que estou disponibilizando a emissão para os bancos: Caixa, Itaú, Santander e Bradesco, você sabe se existe alguma documentação aqui sobre como gerar essas remessas para o banco? me perdoe pela falta de entendimento no assunto, é que nunca precisei fazer esse tipo de integração antes. obrigado!

**Comment by marceloboth** [comment]
O que vc precisa saber para gerar as remessas para os bancos? Falando da gem, para gerar uma remessa vc precisa instanciar a classe de remessa, informar os dados gerais e para cada boleto vai precisar instanciar um objeto pagamento, e passar para a sua instância da remessa.
