### ISSUE TITLE
protesto e baixa automática

### ISSUE THREAD

**Issue by heber28** [kivanio/brcobranca#152]
Bom dia
Eu estou usando essa gem, mas fiquei com uma dúvida quanto ao protesto e baixa dos boletos registrados.
Quando eu envio a remessa eu já envio com os dados de protesto e de baixa dos boletos ou eu tenho que enviar esses dados em remessas separadas?
Segunda dúvida: 
em brcobranca/lib/brcobranca/remessa/cnab240/base.rb
temos os seguintes valores para prostesto e baixa:
segmento_p << '0' # cod. para protesto                   1   *
segmento_p << '00' # dias para protesto                 2   *
segmento_p << '0' # cod. para baixa                         1   *
segmento_p << '000' # dias para baixa                     2   *
Eu vou usar o boleto da Caixa, com remessa cnab240, lá no manual do cnab240 da caixa diz que o código pode ser 1 - para protestar, 3 - não protestar ou 9 para - cancelamento do protesto automatico.
Também no código de baixa, diz que pode ser 1 - para baixar e devolver ou 2 - não baixar e não devolver.
No caso do código, foi setado o valor 0. Esse zero pode ser usado, quando não quero fazer protesto e quando quero dar baixa nos boletos não pagos?
Obrigado desde já

Atenciosamente
Heber

**Comment by esl-douglas** [comment]
+1

**Comment by kivanio** [comment]
Todas as opções estão incluídas.
Vai tudo em um único arquivo remessa.
