### ISSUE TITLE
boleto caixa - convenio

### ISSUE THREAD

**Issue by Luiz-Bernardes** [kivanio/brcobranca#154]
Bom dia,
estou usando o brcobrança, mas estou com um problema e não estou conseguindo resolver.

o boleto caixa que eu preciso gerar tem 11 digitos em convênio mas essa gem só consigo botar 6 digitos em convênio

tentei mudar na própria gem a validação mas creio que isso está gerando outro problema quando o código de barra é gerado e a linha digitável:

tem alguma maneira de resolver isso?

**Comment by danieldenis01** [comment]
Boa tarde, Luiz.

Você provavelmente deve usar o CobCaixa. Para conseguir gerar o boleto você deve solicitar ao seu gerente um novo convênio via SIGCB. Este convênio vai gerar um novo código que vai ser compatível com a quantidade de dígitos necessárias.

Eu passei por esta situação. Via CobCaixa não é possível gerar boletos usando software de terceiros.

**Comment by Luiz-Bernardes** [comment]
Obrigado pela ajuda Daniel,

Então acho que eu estou com um problema, porque eu estou desenvolvendo o site para uma empresa e ela usa o modelo SICOB, tentei solicitar a mudança para o SIGCB mas eles me informaram que não poderia ser feito(pelo que eu entendi envolve custos e coisas do tipo), ainda está sendo estudada pela empresa essa mudança.  Então vou ter que ver se consigo alguma coisa
