### ISSUE TITLE
Linha digitável dos boletos não bate

### ISSUE THREAD

**Issue by PedroVinicius** [kivanio/brcobranca#155]
Eu tenho um CRM aqui que gera o boleto e envia a remessa para o banco. No entanto, este CRM não tem um esquema de envio de boletos por email para cobrança.

Para satisfazer esta necessidade, estou desenvolvendo uma aplicação em ruby para a cobrança. Decidi então utilizar esta gem. O que eu faço basicamente, é acessar a base de dados do CRM, pegar as informações das contas a receber, e então gerar um boleto para cada uma delas. Este sistema proprietáro armazena a linha digitável do boleto e o nosso número. o que me permite conferir se está tudo certo.

Acontece que nenhum dos boletos que eu gero com a Br Cobrança fica com a linha digitável idêntica. Alguns são gerados com parte da linha igual, e outros são gerados com a linha digitável completamente diferente. A informação "nosso número" do boleto sempre sai diferente. Não entendo o que estou fazendo de errado. Vejam o método para gerar o boleto. Ele está dentro de um model.

```ruby
  def generate_bank_slip
    case bank_name
    when :sicoob
      @bank_slip = Brcobranca::Boleto::Sicoob.new
    when :bradesco
      @bank_slip = Brcobranca::Boleto::Bradesco.new
    when :santander
      @bank_slip = Brcobranca::Boleto::Santander.new
    end
    
    @bank_slip.convenio = bank.cod_cedente
    @bank_slip.cedente = bank.nomecedente
    @bank_slip.documento_cedente = bank.cpf_cgc
    @bank_slip.numero_documento = documento
    @bank_slip.sacado = customer.razao_social
    @bank_slip.data_vencimento = Date.parse(vencimento.to_s)
    @bank_slip.data_documento = Date.parse(emissao.to_s)
    @bank_slip.sacado_endereco = customer.complete_address
    @bank_slip.valor = valorhoje.to_f
    @bank_slip.agencia = bank.cod_agencia.to_i
    @bank_slip.conta_corrente = bank.numero_conta.to_i
    @bank_slip.sacado_documento = customer.cpf_cgc
    @bank_slip.carteira = bank.carteira.to_i

    @bank_slip
  end
```
Inspecionando o objeto, tenho a seguinte saída:

```ruby
#<Brcobranca::Boleto::Sicoob:0x0000000411c4d0
 @aceite="S",
 @agencia="3285",
 @carteira=1,
 @cedente="STRING COM A RAZÃO SOCIAL",
 @conta_corrente="0000000",
 @convenio="0000000",
 @data_documento=#<Date: 2017-05-10 ((2457884j,0s,0n),+0s,2299161j)>,
 @data_vencimento=#<Date: 2017-05-22 ((2457896j,0s,0n),+0s,2299161j)>,
 @documento_cedente="00000000000000",
 @especie="R$",
 @especie_documento="DM",
 @local_pagamento="QUALQUER BANCO ATÉ O VENCIMENTO",
 @moeda="9",
 @numero_documento="0103661",
 @quantidade="001",
 @sacado="MUNICIPIO DE BURITI ALEGRE",
 @sacado_documento="01345909000144",
 @sacado_endereco="RUA GOIAS\n" + "\n" + "75660000 - GOIÂNIA / GO",
 @valor=350.0,
 @variacao="01">
```

Verifiquei a validação, e está válido. Será que estou me esquecendo de algum campo?

**Comment by marceloboth** [comment]
@PedroVinicius a linha digitável é problema somente em um determinado banco? Ou é aleatório em todos os bancos? Veja se o valor do convênio é o valor correto para aquele banco, as vezes esse valor faz toda a diferença, o ideal é que confira com a documentação do banco, principalmente para entender como a linha digitável é formada e o nosso número.
