### ISSUE TITLE
Linhas em branco quando gerado remessa pelo Mac + Chrome

### ISSUE THREAD

**Issue by laerciocrestani** [kivanio/brcobranca#157]
Pessoa, bom dia.
Em anexo a imagem que a Caixa me passou. Essa remessa é feita na Web mas pelo Mac, então quando eles analisaram, ficou com linhas em branco. Eu abri pelo windows + Chrome, ficou normal sem as linhas, passando pelas validações da caixa.

Alguém passou por isso?
![image](https://cloud.githubusercontent.com/assets/1430869/26493778/e58230b4-41f1-11e7-8024-ad2acb8466be.png)

Fiquem com Deus.

**Comment by kivanio** [comment]
Você abriu o arquivo no MAC antes de enviar a Caixa?

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2017-05-26 8:02 GMT-04:00 Laércio Crestani <notifications@github.com>:

**Comment by laerciocrestani** [comment]
Não. Ele baixa o txt nas transferencias e encaminho direto, sem abri-lo.

**Comment by kivanio** [comment]
Teste usar isso ao fazer o download do arquivo no seu controller.
Se funcionar, incluo na gem.

send_data conteudo_remessa.encode(‘windows-1252’), type: ‘text/txt;
charset=windows-1252', disposition: "attachment; filename=#{remessa.rem}"

O problema é que os programas de banco usam encode do windows.


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by laerciocrestani** [comment]
To fazendo pelo:
send_data caixa.gera_arquivo, :content_type => 'text/plain', :filename => "remessa.txt"

**Comment by kivanio** [comment]
Só coloca o encode:
send_data caixa.gera_arquivo.encode(‘windows-1252’), type: ‘text/txt;
charset=windows-1252', disposition: "attachment; filename=#{remessa.rem}"

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by laerciocrestani** [comment]
Sim, foi certinho o encode, mas as linhas em branco persistem...

**Comment by kivanio** [comment]
As linhas só aparecem no mac após abrir o arquivo.
O mac, não sei porque, ao abrir já troca para espaços.
Imagino que seja porque o padrão entre os SOs são diferentes para o fechamento de linhas.
Se você não abrir o arquivo, fica tudo bem.
