### ISSUE TITLE
Gem não faz o parse de Código de Movimento Retorno e Motivo da Ocorrência para CNAB 240

### ISSUE THREAD

**Issue by ronyvieira** [kivanio/brcobranca#158]
Tive um problema com um boleto que não foi registrado no banco e não consegui saber porque isso tinha ocorrido. Ao ler o arquivo de retorno vi que a informação estava lá no código e motivo porém não consegui obter essa informação através da gem.

Há algum motivo para essa informação não ser processada pela gem?

**Comment by kivanio** [comment]
Rony,

apenas necessita de contribuição para que possa ser feito.
Faça e nos envie um patch! \o/

Kivanio

2017-05-30 16:03 GMT-04:00 Rony Vieira <notifications@github.com>:

**Comment by ronyvieira** [comment]
@kivanio vou fazer e envio assim que puder então...

A questão de não ter juros e multa na remessa também é falta de tempo ou encontrou alguma restrição?

**Comment by kivanio** [comment]
Tudo é falta de alguém gastar um tempo fazendo.
Só isso.

Cada um faz o que tem necessidade e envie PR para disponibilizar.
Ninguém precisou ou não quis colaborar ainda. :)

Att,
Kivanio


2017-05-30 16:51 GMT-04:00 Rony Vieira <notifications@github.com>:

**Comment by marceloboth** [comment]
Eu fiz na empresa onde trabalho, mas fiquei mandando para homologação e corrigindo as frescuras dos bancos, acabei nao mandando os PR's acumulando tudo. Tenho tudo isso feito (Mora, multa, protesto, código de ocorrencia, retornos e remessa que faltam no projeto).

 Assim como todos, estou lascado de tempo pra mandar para cá. Se alguem puder me ajudar podemos mandar para cá https://github.com/monde-sistemas/brcobranca.

**Comment by ronyvieira** [comment]
Legal @marceloboth! 
Vi que você fez muita coisa! O problema é que seu branch tá distante do master aqui (291 commits ahead, 150 commits behind). Não sei se será muito simples fazer o merge por causa do 150 behind. Deu muito conflito quando você tentou? Você já tá rodando essas alterações homologadas em quais bancos?

**Comment by marceloboth** [comment]
Sim deu bastente problema. As alterações e implementações que fiz estão rodando nos nossos clientes e estão homologadas com as carteiras registradas. Os bancos homologados são: Caixa, BB, Itau, Santander, Bradesco, Sicoob, Sicredi, Unicred (Integrado com Sicredi), Banrisul. Não homologados: Banco do Nordeste, Banco de Brasilia, Cecred e Credisis.

**Comment by ronyvieira** [comment]
@marceloboth tentei fazer o merge no seu mas você implementou muita coisa e ficou complicado. Estou usando ele como referência para ir incorporando aos poucos suas alterações...

**Comment by ronyvieira** [comment]
@brunnohenrique tive esse problema com urgência e também tive que implementar. Infelizmente não pude esperar a gem incorporar a solução. Fiz um pull request mas não foi aceito então estou pensando em criar uma gem independente pois os problemas precisam ser resolvidos com urgência. Ainda mais se tratando de assuntos financeiros.

**Comment by marceloboth** [comment]
E eu tenho um fork com quase tudo implementado, essa parada da ocorrência e motivos das ocorrências de forma bem simples eu tenho feito. As remessas tenho todas homologadas, pois a Monde (Empresa que trabalho), emite todos os boletos por essa gem e contempla mais de 11 bancos com carteira com registro. Porém eu esbarro no envio dos PR's para cá, tenho muita coisa feita, o @ronyvieira viu nesses dias, e devido a correria que deu para fazer, homologar, acabei ficando de enviar os PR's e no fim deu maior conflito. 

@brunnohenrique vou ver se consigo trazer essa parte dos retornos para a master do BRCobranca. @ronyvieira o ideal não seria criar uma gem separada, para a mesma coisa, entendo seu lado, mas o melhor seria uma gem só com todos os membros ativos, do que N gems.

@kivanio se vc precisa de alguém para ajudar a manter a gem junto com vc estou a disposição.

**Comment by ronyvieira** [comment]
@marceloboth concordo com você. O ideal é unir esforços pra termos algo sólido com a contribuição de todos. Isso evitaria muito esforço duplicado que estamos tendo... 
Mas para isso a comunidade teria que ser mais ativa e a manutenção mais constante. Senão acaba acontecendo como o caso da Monde que, apesar de ainda ser um fork, já está tão diferente que é bem complexo fazer o merge das melhorias.

**Comment by rvalyi** [comment]
pessoal, nao sei bem onde promover isso, mas fiz um mirco-service com o brcobranca gem para usa-lo com qualquer linguagem: https://github.com/akretion/boleto_cnab_api
No caso estamos usando com o ERP open source Odoo (que eh em Python) que adaptamos para o Brasil.
De repente divulgar esse micro-service poderia ajudar a agregar mais pessoas para contribuir no projeto brcobranca... cc @kivanio

**Comment by kivanio** [comment]
Pessoal,

o problema é que todo mundo faz urgente pra si próprio, mas o PR nunca chega :)
Ou chega quebrando teste ou sem testes, ai é complicado.

Se eu ganhasse um R$ 1,00 toda vez que alguém fala comigo por aqui, emails e etc e nunca retorna com nada, estava milionário!

É só fazer o PR que não há problema nenhum em dar merge.

Eu mesmo, quando tenho tempo, olho os forks e pego coisas deles e incorporo na gem.

A questão é simples, ter tempo e fazer os PR corretos para merge.

Tem mais gente que da merge no projeto, acho que a questão não é essa.
É os PR chegarem, depois chegarem certos e não bagunçado para alguém ter que ir arrumar para dar merge.

@brunnohenrique Isso não é problema da gem, a gem só ter que fazer o parser e trazer todas as linhas do arquivo. Existem vários códigos de retorno/remessa.
Depois com as linhas, é sua aplicação que tem que filtrar o que interessa.

@marceloboth Vou te add de committer

@rvalyi Muito TOP! Manda um PR com ele no README pra deixar divulgado 👍 
Se eu entendi ele usa GET, talvez seria melhor usar POST, por segurança dos dados e com GET dependendo do tamanho da url você terá problemas com CDN e outras coisas, pois há um limit de bytes na chamada GET.

**Comment by ronyvieira** [comment]
Boa noite, @kivanio. Entendo que seja difícil manter tudo sozinho. Em relação a essa thread eu fiz um PR em julho. Então não fiz pra mim próprio. O PR não estava quebrando os testes também e aumentou a cobertura de teste. Se algo não estava de acordo com o que pensa do futuro da gem, teria maior prazer em discutir e alterar. Acho que adicionar mais pessoas como committer é bem válido. Como o @marceloboth está sempre presente nas discussões acho que ele é um cara que vai agregar muito ao projeto.  

Sempre quis contribuir com a gem mas, assim como a Monde, não posso esperar meses para que as melhorias sejam adicionadas ao projeto. Nunca tive a intenção de desenvolver algo paralelo, mas chega a um ponto que temos que tomar essa decisão, mesmo que a contra gosto. Creio que foi o caso da Monde também pois ninguém tem a intenção de ter um fork com 300 commits ahead e 163 commits behind.

De qualquer forma ainda quero contribuir com o projeto para que possamos construir algo que todos possam se beneficiar. Podem contar comigo pra evolução.

**Comment by marceloboth** [comment]
Blz galera, ótimo ver a opinião de vcs todos, vou tentar ajudar ao máximo aqui, trazendo tudo que temos na Monde, fechando essas issues abertas e dar um gás nesses PR's que estão abertos.

**Comment by rvalyi** [comment]
@kivanio vou fazer um PR para indicar o servico no README, tava pensando na mesma coisa. Na vdd ja usamos POST para quasi tudo, como indicado no codigo https://github.com/akretion/boleto_cnab_api/blob/master/lib/boleto_api.rb Mas de repente posso tb converter tudo para POST.

Sobre ganhar um 1R$ de cada vez, depois precisamos conversar. O Odoo ainda ta fraco no Brasil mas a gente ta aqui para mudar isso :-) . Agora fizeram um lance de in-apps payment que vc gasta creditos sempre que usa algum servico. Acho que seria uma boa conectar com o boletosimples de voces e nao deve ser tao diferente do que eu ja fiz para connectar ao brcobranca. Eu saberia fazer isso numa boa e cada um pode ganhar com isso. Enfim apenas o dia que o Odoo detonar a Totvs rsrsrs, mas nao tem muito porque isso nao acontecer.
