### ISSUE TITLE
Juros de mora na remessa para CNAB240 não está implementado

### ISSUE THREAD

**Issue by ronyvieira** [kivanio/brcobranca#159]
O campo de juros de mora não está implentando para remessas do tipo 240.

**Código do Juros de Mora (C018)**  
Código adotado pela FEBRABAN para identificação do tipo de pagamento de juros de mora.
Domínio:
'1' = Valor por Dia
'2' = Taxa Mensal
'3' = Isento 

**Data do Juros de Mora (C019)**
Data indicativa do início da cobrança do Juros de Mora de um título de cobrança.
A data informada deverá ser maior que a Data de Vencimento do título de cobrança
Caso seja inválida ou não informada será assumida a data do vencimento.
Utilizar o formato DDMMAAAA, onde:
DD = dia
MM = mês
AAAA = ano

**Juros de Mora por Dia / Taxa (C020)**
Valor ou porcentagem sobre o valor do título a ser cobrada de juros de mora.

**Comment by ronyvieira** [comment]
Boa noite @kivanio,

Reparei que no objeto de pagamento há atributos específicos do CNAB400, como por exemplo primeira instrução e não há outros como o código de juros de mora do CNAB240.

Acha que seria uma boa idéia separar os dois tipos de pagamento deixando no pai apenas as coisas comum?

**Comment by jonathanbruno** [comment]
@ronyvieira Você pegou pra fazer isso, ou apenas abriu o tópico?

**Comment by ronyvieira** [comment]
@jonathanbruno Estou fazendo em um fork. Já estou testando no Banco do Brasil... Fiz apenas a parte do Cnab240, ainda não separei os objetos de pagamento 240 e 400. Você implementou essa parte também?

**Comment by jonathanbruno** [comment]
@ronyvieira Não comecei nada ainda, tava só olhando os issues mesmo, talvez eu comece outro banco

**Comment by ronyvieira** [comment]
@jonathanbruno na teoria a implementação é a mesma mas é bom validar na prática.... Ainda pretendo validar com o Sicoob. Com a Caixa não conseguirei.

**Comment by ronyvieira** [comment]
@jonathanbruno testei com o Sicoob e as alterações funcionaram lá porém para CNAB240 é preciso incluir o DV no nosso número. Fiz a correção mas não posso fazer um pull request pois minhas alterações anteriores não foram adicionadas aqui. De qualquer forma se passar por esse problemas pode verificar minha implementação no meu fork.

**Comment by kivanio** [comment]
Na verdade, deveria ser extraído um novo Pagamento para conter coisas específicas do 240.
Dentro do 400 também tem várias coisas que deveriam ser extraídas.

Vou fechar a issue, acho que no novo código tem essas instruções.
Se sentir falta de algo manda o PR ou abra uma issue.
