### ISSUE TITLE
Remessa e retorno 240 do Sicoob não estão utilizando o DV no nosso número

### ISSUE THREAD

**Issue by ronyvieira** [kivanio/brcobranca#164]
Tentei registrar uma remessa no Sicoob gerada pela gem e recebi que o código de nosso número era inválido. Vi que é necessário incluir o DV no nosso número para gerar a remessa.

Fiz a correção em meu fork e consegui registrar os boletos com sucesso.

**Comment by raphagood** [comment]
@ronyvieira tem um exemplo de arquivo de remessa para me enviar, com o nosso número, estou tendo a mesma dificuldade.

**Comment by ronyvieira** [comment]
Olá @raphagood 
Desculpe a demora. Há um tempo que fiz essas alterações. Não lembro como foi resolvido mas creio que adicionei uma verificação para adicionar o nosso número manualmente no caso do sicoob. Se ainda estiver precisando me avise que posso ver isso pra ti hoje à noite.
