### ISSUE TITLE
Como trabalhar com a carteira 17-019 do Banco do Brasil na gem brcobranca?

### ISSUE THREAD

**Issue by Losangelo** [kivanio/brcobranca#167]
Olá a todos, alguém está trabalhando com esse tipo de carteira, 17-019 banco do Brasil?

Já que o tamanho padrão para a carteira é de 2 dígitos.

Alguma dica?

Resolvido: Dica de Marcelo Both
Só informa no campo variação
@boleto.variacao = '19'

Obrigado!

**Comment by marceloboth** [comment]
@Losangelo se estiver resolvido, por favor feche a issue.
