### ISSUE TITLE
Documentação e Wiki

### ISSUE THREAD

**Issue by jonathanbruno** [kivanio/brcobranca#169]
Eu percebi que o wiki está um pouco desatualizado com relação ao código, pelo que eu vi tem mais remessa 400 do que os citados na wiki. Pode alterar?

Outra coisa, seria interessante ter na pasta do projeto os layouts de remessa/retorno de cada banco para facilitar a busca por informações de layout e também diminuir o risco de alguém utilizar o layout errado.
Acho que isso ficaria bem na pasta arquivos.

Não sei quanto à wiki, mas vou fazer um pull request adicionando os layout de remessa/retorno.

**Comment by kivanio** [comment]
Pode alterar tudo, a gem é feita por quem usa e contribui, se quiser contribuir, agradeço.
