### ISSUE TITLE
CNAB400 ITAÚ - Arquivo de remessa excedendo as 400 posições na segunda linha

### ISSUE THREAD

**Issue by ademir10** [kivanio/brcobranca#170]
Boa tarde!
Estou tendo um probleminha ao gerar o arquivo de remessa para o Itaú usando o CNAB400, na segunda linha é excedido o limite maximo de posições e é repetido o numero da linha 3 na linha 2, o meu arquivo está ficando assim no final das linhas 1 e 2:
000001
00000003 000002
é somente isso que está errado, alguém saberia me dizer o que eu posso fazer para resolver este problema?
Ontem o Kivanio até me mandou um exemplo sobre como gerar o arquivo e estou utilizando exatamente o mesmo arquivo.. Estou dando uma olhada no conteúdo da Gem para tentar encontrar o erro mais não encontrei nada.

Este é o meu código`
# criação de um pagamento válido
  pagamento = Brcobranca::Remessa::Pagamento.new(valor: dados_boleto.valor_doc,
                                                 data_vencimento: dados_boleto.data_vencto,
                                                 nosso_numero: dados_boleto.id,
                                                 documento_sacado: dados_boleto.destinatario.cpf_cnpj,
                                                 nome_sacado: dados_boleto.destinatario.nome_destinatario,
                                                 endereco_sacado: dados_boleto.destinatario.logradouro_destinatario + ' ' + dados_boleto.destinatario.numero_destinatario,
                                                 bairro_sacado: dados_boleto.destinatario.bairro_destinatario,
                                                 cep_sacado: dados_boleto.destinatario.cep_destinatario.remove("-"),
                                                 cidade_sacado: dados_boleto.destinatario.municipio_destinatario,
                                                 uf_sacado: dados_boleto.destinatario.uf_destinatario)

  # criação da instância
  itau = Brcobranca::Remessa::Cnab400::Itau.new(carteira: dados_boleto.banco.carteira,
                                                        agencia: dados_boleto.banco.agencia,
                                                        conta_corrente: dados_boleto.banco.conta_corrente,
                                                        digito_conta: dados_boleto.banco.digito,
                                                        empresa_mae: dados_empresa.razao,
                                                        documento_cedente: cnpj_empresa,
                                                        pagamentos: [pagamento])
  # criação da remessa
  remessa = itau.gera_arquivo
  send_data itau.gera_arquivo, :content_type => 'text/plain',
                                 :filename => "remessa.txt"`

Se alguém puder pelo menos me dizer onde eu poderia verificar eu ficaria inteiramente agradecido.
E obrigado mais uma vez ao Kivanio que disponibilizou esta excelente GEM!

**Comment by jonathanbruno** [comment]
O interessante é não permitir gerar um arquivo fora do formato correto

**Comment by ademir10** [comment]
Então Jonathan eu tentei verificar na Gem se eu encontrava o arquivo que é responsável pela geração do arquivo mais não encontrei, você saberia me dizer com base nesse erro onde eu poderia verificar? Brigadao Man

**Comment by kivanio** [comment]
A gem não limite o tamanho dos campos que você passa.
Você precisa descobrir qual dado você está passando com tamanho errado e corrigir.
Todos os tamanhos estão no código, basta olhar:
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/cnab400/itau.rb#L86
