### ISSUE TITLE
Como inserir vários boletos no mesmo arquivo de remessa?

### ISSUE THREAD

**Issue by ademir10** [kivanio/brcobranca#171]
Boa noite, estou tentando gerar um arquivo de remessa com dados de vários boletos gerados, é possível?
Exemplo, fiz uma venda de R$1.000,00 e parcelei no boleto em 4 vezes de R$250,00. Até ai tudo bem, estou gerando os 4 boletos no mesmo PDF, porém não estou conseguindo inserir as informações dos 4 boletos no mesmo arquivo de remessa.

Alguém saberia dizer se é possível e se existe algum exemplo? tentei com um Hash mais recebo uma mensagem dizendo que não é possível.
Obrigado.

**Comment by marceloboth** [comment]
O objeto pagamento representa seu boleto. Tem que passar os dados dos seus boletos para o objeto pagamento, se for mais de um cria uma lista e manda junto na remessa.

**Comment by ademir10** [comment]
Obrigado pelo retorno marceloboth! eu estou tentando desta forma, mais recebo a seguinte mensagem:
Pagamentos cada item deve ser um objeto Pagamento.
  'hash_dados = Brcobranca::Remessa::Pagamento.new(
                   valor: dados_boleto.valor_doc,
                   data_vencimento: data_vencto,
                   nosso_numero: dados_boleto.id,
                   documento_sacado: cnpj_sacado,
                   nome_sacado: dados_boleto.destinatario.nome_destinatario,
                   endereco_sacado: dados_boleto.destinatario.logradouro_destinatario + ' ' + dados_boleto.destinatario.numero_destinatario,
                   bairro_sacado: dados_boleto.destinatario.bairro_destinatario,
                   cep_sacado: dados_boleto.destinatario.cep_destinatario.remove("-"),
                   cidade_sacado: dados_boleto.destinatario.municipio_destinatario,
                   uf_sacado: dados_boleto.destinatario.uf_destinatario)
  # criação de um pagamento válido
  @dados_boleto = hash_dados  
  @boletos << @dados_boleto
  qnt_parcelas = qnt_parcelas - 1
end
  # criação da instância
  itau = Brcobranca::Remessa::Cnab400::Itau.new(carteira: dados_boleto.banco.carteira,
                                                        agencia: dados_boleto.banco.agencia,
                                                        conta_corrente: dados_boleto.banco.conta_corrente,
                                                        digito_conta: dados_boleto.banco.digito.to_s,
                                                        empresa_mae: dados_empresa.razao,
                                                        documento_cedente: cnpj_empresa,
                                                        pagamentos: [@boletos])'

Conseguiria me mandar um exemplo?

**Comment by ademir10** [comment]
tentei passar os dados dos boletos dessa forma também e não rola:
`  # criação de um pagamento válido
  boleto_dados =   { valor: dados_boleto.valor_doc,
                   data_vencimento: data_vencto,
                   nosso_numero: dados_boleto.id,
                   documento_sacado: cnpj_sacado,
                   nome_sacado: dados_boleto.destinatario.nome_destinatario,
                   endereco_sacado: dados_boleto.destinatario.logradouro_destinatario + ' ' + dados_boleto.destinatario.numero_destinatario,
                   bairro_sacado: dados_boleto.destinatario.bairro_destinatario,
                   cep_sacado: dados_boleto.destinatario.cep_destinatario.remove("-"),
                   cidade_sacado: dados_boleto.destinatario.municipio_destinatario,
                   uf_sacado: dados_boleto.destinatario.uf_destinatario }

  retorno = Brcobranca::Remessa::Pagamento.new(boleto_dados)

  # criação de um pagamento válido
  @dados_boleto = retorno
  @boletos << @dados_boleto
  qnt_parcelas = qnt_parcelas - 1
end`

**Comment by ademir10** [comment]
Pelo menos poderia me enviar um exemplo de como criar a lista Marcelo? manualmente eu consegui fazer os dados serem inseridos no arquivo de remessa, agora não sei como criar a lista.

**Comment by marceloboth** [comment]
Da uma olhada nesse teste, a idéia é bem essa que o pessoal usa no teste: https://github.com/kivanio/brcobranca/blob/master/spec/brcobranca/remessa/cnab400/itau_spec.rb#L28.

**Comment by ademir10** [comment]
Brigadão Marcelo! vou dar uma olhada com calma amanhã pra ver se eu consigo entender e aplicar a minha necessidade. amanhã dou um toque dizendo se resolveu, valeu!

**Comment by ademir10** [comment]
Bom dia Marcelo!
dei uma olhada aqui no exemplo que você me mandou o link e fiquei um pouco confuso com a parte do código que você comentou, porque pelo que eu entendi, quando eu gero um arquivo de remessa, os dados que são inseridos no arquivo de remessa a cada boleto emitido, vem do objeto PAGAMENTO não é? nesse caso eu não precisaria de algo como um DO While para extrair somente esses dados da query e passar para a lista? me desculpe pela falta de entendimento, mais é que essa é a minha primeira necessidade em passar dados através de uma lista, então te confesso que estou completamente perdido. Se puder mandar uma luz eu agradeceria.
Essa foi a parte do código que você comentou né?  let(:itau) { subject.class.new(params) }

Uma outra pergunta, é possível enviar por email o PDF gerado ao cliente? eu uso a gem WickedPDF para gerar e enviar automaticamente orçamentos, porém é preciso ter uma view como layout para que o PDF seja gerado e anexado, como no exemplo abaixo:
"contrato_pdf = WickedPdf.new.pdf_from_string(render_to_string pdf: "contrato", template: "pdf_mailer/contrato.html.erb")
   attachments['Contrato ' + "#{invoice.destinatario.nome_destinatario}.pdf"] = contrato_pdf"
Obrigado.

**Comment by marceloboth** [comment]
@ademir10 no Brcobranca a remessa é composta de duas partes: O objeto remessa e uma lista de objetos pagamentos. O objeto remessa vai ter os dados globais, como banco, agencia e os dados do emissor. O pagamento é sua lista de boletos que você quer registrar. Nele vai os dados do boleto: nosso numero, valor, vencimento, mora e demais coisas especificas do título. 

Pra gerar a remessa com um boleto, você teria que instanciar a classe pagamento, passar os dados, depois disso instanciar a classe Remessa e nela passar para o campo pagamentos o(s) seu(s) boleto(s).

Se você tem uma lista de boletos, é necessário iterar sobre eles, e então passar dados de cada um dos boletos para um objeto pagamento, pois os objetos boleto e pagamento não são iguais na Gem.

**Comment by ademir10** [comment]
eu tentei passar os dados de cada boleto através de um hash mais não rola, diz que o objeto Pagamento não aceita.. e que eu preciso passar cada pagamento separadamente, por isso que fiquei perdido nesse exemplo de lista que você me mandou. 

É exatamente aqui que eu não sei como armazenar os boletos Marcelo:
`boleto_dados = Brcobranca::Remessa::Pagamento.new( valor: dados_boleto.valor_doc,
                   data_vencimento: data_vencto,
                   nosso_numero: dados_boleto.id,
                   documento_sacado: cnpj_sacado,
                   nome_sacado: dados_boleto.destinatario.nome_destinatario,
                   endereco_sacado: dados_boleto.destinatario.logradouro_destinatario + ' ' + dados_boleto.destinatario.numero_destinatario,
                   bairro_sacado: dados_boleto.destinatario.bairro_destinatario,
                   cep_sacado: dados_boleto.destinatario.cep_destinatario.remove("-"),
                   cidade_sacado: dados_boleto.destinatario.municipio_destinatario,
                   uf_sacado: dados_boleto.destinatario.uf_destinatario)
  end`

Eu tentei passar todos os boletos para uma variável como abaixo e ele não permite:
do while...
@boletos[]
todos_boletos = { aqui vão todos os dados dos boletos }
end
@dados_boleto = Brcobranca::Boleto::Itau.new(todos_boletos)
@boletos << @dados_boleto

Eu pensei que desta forma eu conseguiria mais ele não permite, diz que é preciso passar cada pagamento de uma vez.. consegue mandar alguma luz meu brother?

**Comment by marceloboth** [comment]
O seu boleto_dados tem que ser passadao para o atributo pagamentos da instancia da remessa. Abaixo um exemplo com dois boletos:

```
boleto_um = Brcobranca::Remessa::Pagamento.new
boleto_dois = Brcobranca::Remessa::Pagamento.new
remessa = Brcobranca::Remessa::Cnab400::Itau.new
remessa.pagamentos = [boleto_um, boleto_dois]
```

**Comment by ademir10** [comment]
foi exatamente o que eu consegui fazer, achei que conseguiria passar os dados de todos os boletos aproveitando a mesma variável.
Brigadão pelo toque Marcelo! com relação ao envio automático por email do PDF seria possivel? ou obrigatóriamente precisa ser salvo e depois enviado?

**Comment by marceloboth** [comment]
Sim é. Vc vai ter um mailer de enviou, certo? precisa só colocar o pdf como attachment.

**Comment by ademir10** [comment]
no momento em que eu gero o boleto eu preciso primeiro salvar ele em uma pasta e depois passar o caminho então?
porque na geração de orçamentos eu gerava o pdf com base em um template e ai passava como anexo assim:

contrato_pdf = WickedPdf.new.pdf_from_string(render_to_string pdf: "contrato", template: "pdf_mailer/contrato.html.erb")
attachments['Contrato ' + "#{invoice.destinatario.nome_destinatario}.pdf"] = contrato_pdf"

**Comment by marceloboth** [comment]
@ademir10 sobre essa parte do anexo do PDF, é relacionado ao próprio Rails e não a gem, estou fechando essa issue.
