### ISSUE TITLE
Problema ao gerar boleto não registrado

### ISSUE THREAD

**Issue by matheusb982** [kivanio/brcobranca#176]
Usando as configurações da documentação, só estou conseguindo gerar boleto com código 14 no 'Nosso número', mais preciso gera boleto não registrado com código 24.

![asddf](https://user-images.githubusercontent.com/18557872/31682529-b98c5ea0-b350-11e7-9611-b085623bd531.png)

**Comment by kivanio** [comment]
Precisa enviar o parametro correto "2":
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/boleto/caixa.rb#L26

**Comment by matheusb982** [comment]
Deu certo, muito obrigado.
