### ISSUE TITLE
Cálculo de DV de cooperativa Sicoob está mapeando para X ao invés de 0

### ISSUE THREAD

**Issue by ronyvieira** [kivanio/brcobranca#178]
Ao calcular o DV da cooperativa Sicoob a gem está mapeando para X sendo que deveria estar mapeando para 0.

Por exemplo:
Segundo a documentação do banco, a agência '3214' tem DV '0'

**Comment by marceloboth** [comment]
@ronyvieira sim, está errado. Eu corrigi isso no meu branch ontem e pretendo mandar essa semana para cá.

**Comment by ronyvieira** [comment]
@marceloboth Eu vi a alteração no seu  :+1: :+1: :+1: e registrei aqui pra tentar manter atualizadas as issues aqui também.

Você chegou a alterar o CNAB 400 também? O código está duplicado lá.
Seria legal refatorar as classes para que as funções comuns não sejam duplicadas também.

**Comment by kivanio** [comment]
resolvido?

**Comment by ronyvieira** [comment]
Ainda não @kivanio ... Quer que faça um PR?
