### ISSUE TITLE
Documentações

### ISSUE THREAD

**Issue by kivanio** [kivanio/brcobranca#182]
@marceloboth @ronyvieira @mbcosta  
Vocês poderiam anexar as documentações que vocês tem aqui na issue?

Vou colocar no repositório para consulta, mas não entrarão na gem compilada.
Pensei e acho que vai ser o melhor lugar.

No momento não dá para saber com que documentação tal coisa foi feita.
Pretendo resolver isso, e a partir disso, qualquer alteração, tem que estar em alguma documentação dentro da gem para conferência.

**Comment by ronyvieira** [comment]
Acho uma boa ideia. Assim, mesmo com a evolução dos padrões e com as alterações nas documentações, vamos conseguir ter rastreabilidade das evolução do código.

Não sei se são as últimas versões mas segue as que tenho aqui

CNAB 240
[banco_do_brasil_particularidades_CbrVer04BB.pdf](https://github.com/kivanio/brcobranca/files/1539230/banco_do_brasil_particularidades_CbrVer04BB.pdf)

[febraban_swift15-layout padrao V 09 00 - 02_03.pdf](https://github.com/kivanio/brcobranca/files/1539231/febraban_swift15-layout.padrao.V.09.00.-.02_03.pdf)

[Manual_Leiaute_CNAB240_SIGCB.pdf](https://github.com/kivanio/brcobranca/files/1539233/Manual_Leiaute_CNAB240_SIGCB.pdf)

CNAB 240 e 400
[sicoob_cnab.xlsx](https://github.com/kivanio/brcobranca/files/1539245/sicoob_cnab.xlsx)

CNAB 400
[banco_do_brasil_Doc2627CBR641Pos7.pdf](https://github.com/kivanio/brcobranca/files/1539249/banco_do_brasil_Doc2627CBR641Pos7.pdf)

[caixa_Manual_Leiaute_CNAB400_SIGCB.pdf](https://github.com/kivanio/brcobranca/files/1539250/caixa_Manual_Leiaute_CNAB400_SIGCB.pdf)

[hsbc_cob400_jan.pdf](https://github.com/kivanio/brcobranca/files/1539251/hsbc_cob400_jan.pdf)

[safra_cobranca2016.pdf](https://github.com/kivanio/brcobranca/files/1539252/safra_cobranca2016.pdf)

**Comment by mbcosta** [comment]
ola @kivanio , parabéns pelo excelente trabalho

Bradesco - Boleto, CNAB400 Remessa e Retorno
https://banco.bradesco/assets/pessoajuridica/pdf/4008-524-0121-layout-cobranca-versao-portugues.pdf

**Comment by kivanio** [comment]
@marceloboth @aryrabelo Você podem anexar as documentações do CREDISIS, UNICRED, CECRED e os outros cred's que tenham? 👍

**Comment by marceloboth** [comment]
[CECRED](https://github.com/kivanio/brcobranca/files/1542715/MI.-.CBB.-.Manual.CNAB.240.pdf)

[Unicred Cnab 240](https://github.com/kivanio/brcobranca/files/1542719/Sicredi.Manual.Cnab.240.pdf)

[Sicredi Cnab 240](https://github.com/kivanio/brcobranca/files/1542719/Sicredi.Manual.Cnab.240.pdf)

**Comment by marceloboth** [comment]
@kivanio sim, a cnab 240 é igual ao sicredi e o boleto é o mesmo layout, somente com a logo e numero do "banco" unicred.
