### ISSUE TITLE
Erro ao ler campo nosso_numero do arquivo de retorno Bradesco.

### ISSUE THREAD

**Issue by gnumarcelo** [kivanio/brcobranca#183]
Primeiramente obrigado por escrever esta gem, tem sido de grande valia!

Estou tentando ler o arquivo CNAB400 (o mesmo que esta no diretorio do rspec CNAB400BRADESCO.RET) porém o mesmo está retornando `00000000` no campo `payment.nosso_numero`mas segundo o arquivo de teste `retorno/cnab400/bradesco_spec.rb` este campo deveria ter o valor '000000000303'.

Sabem se isso é um problema na gem ou no arquivo de retorno?

**Comment by kivanio** [comment]
Pelo que conferi aqui agora, a gem está ok. E o teste diz isso.
Se abrir um arquivo CNAB400BRADESCO.RET e ir na posicao 70 da primeira linha, verá que o valor é igual ao teste.

Está lendo o arquivo correto? 
Passando o caminho completo correto?

**Comment by gnumarcelo** [comment]
Tem razão @kivanio , eu estava usando `Brcobranca::Retorno::RetornoCnab400` para ler o arquivo, enquanto que o certo seria utilziar a classe `Brcobranca::Retorno::Cnab400::Bradesco`.

Obrigado pela resposta e pelo excelente trabalho na gem!
