### ISSUE TITLE
Arquivo Remessa Itau

### ISSUE THREAD

**Issue by smorigo** [kivanio/brcobranca#185]
Boa tarde pessoal tudo bem?
Estou com um sistema em produção onde utilizava a gem 8.0.0 para gerar o arquivo de remessa.

Fiz essa semana a atualização da gem para a ultima versão e 2 linhas do arquivo de remessa ficaram desalinhados, alguém já identificou algo do tipo ?

**Comment by smorigo** [comment]
Pessoal, acredito ter identificado o problema, quando envio os dados com "."

**Comment by cassiopagnoncelli** [comment]
Mesmo problema aqui. Meu problema foi o seguinte: se o endereço tiver ponto (.), ele fica desalinhado. Resolvi assim:

```
endereco = I18n.transliterate(endereco).to_s.gsub(/[^0-9A-Za-z ,]/i, '').strip
```

**Comment by kivanio** [comment]
Manda um PR ;)

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by cassiopagnoncelli** [comment]
@kivanio WIll do :)

**Comment by cassiopagnoncelli** [comment]
Feito @kivanio. Por favor, checar diligentemente, é meu primeiro PR :)

**Comment by escobera** [comment]
Estou com o mesmo problema. @kivanio Tem como dar uma olhada no pull #189 do @cassiopagnoncelli ? O código me parece suficiente pra corrigir o problema.

**Comment by kivanio** [comment]
Olá, isso foi corrigido há algum tempo.
Até coloquei um commit hoje pra testar:
https://github.com/kivanio/brcobranca/commit/f8360a38afae27f7e996e889f27ffe6a4685da77

Preciso de um teste quebrando para ver se está com problema.
Só fornecer um teste que vejo.
