### ISSUE TITLE
Remessa para atualização de campos

### ISSUE THREAD

**Issue by mrluizandre** [kivanio/brcobranca#186]
Olá a todos! Primeiramente quero agradecer a todos que contribuem para esse projeto, é de grande valia no meu trabalho.

**Vamos a dúvida**
Atualmente trabalho com cobranças do Itaú. Geração de boleto, remessas e análise de retorno funcionando OK.

Agora surgiu a necessidade de enviar uma atualização de determinado boleto em uma nova remessa para o banco, com atualização de data de vencimento ou valor por exemplo. Seria como uma "remessa de atualização".

Gostaria de saber se há algo feito na gem com esse propósito ou mesmo se alguém que já fez algo do tipo e poderia dar uma luz em relação a isso.

No manual do Itaú tem algumas orientações a cerca disso, só gostaria de saber se já foi feito antes por alguém.

Obrigado.

**Comment by kivanio** [comment]
Andre,

o que diz o tipo do registro é esse parâmetro:
https://github.com/kivanio/brcobranca/blob/master/lib/brcobranca/remessa/pagamento.rb#L31

O que você precisa descobrir é qual o código do banco você tem que mandar
para a operação que você quer fazer.
Basta passar o código correto na instância do Pagamento, o restante deve
funcionar sem problemas.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2018-01-17 15:40 GMT-03:00 Andre Costa <notifications@github.com>:

**Comment by mrluizandre** [comment]
Muito obrigado pela informação @kivanio, vou testar com meu projeto. ✌
