### ISSUE TITLE
RetornoCnab240

### ISSUE THREAD

**Issue by laerciocrestani** [kivanio/brcobranca#187]
Pessoal, o load_lines esta retornando como vazio []

`
records = Brcobranca::Retorno::RetornoCnab240.load_lines('public/uploads/financeiro/retorno/arquivo/47/r1000002.ret')
`
`logger.info records`

Estou usando um .RET da CAIXA em CNAB 240

**Comment by marceloboth** [comment]
@laerciocrestani tenta chamar a classe da caixa direto, sem chamar pela classe base. Acredito que temos um bug ai. Pois geralmente, ao chamar a classe base, ela encontra a classe correta e retorna os dados do retorno, e para o retorno da caixa, pode ser que está com problema.

**Comment by laerciocrestani** [comment]
Retorna []
mesmo usando
`Brcobranca::Retorno::Cnab240::Caixa.load_lines(file)`

**Comment by marceloboth** [comment]
Tentou com outro banco para ver se é somente problema com o retorno da Caixa? Me parece ser especifico da caixa, pois ela reescreve os campos de forma diferente dos demais.

**Comment by marceloboth** [comment]
O caso do bradesco seria esse chamada, respeitando os namespaces: 

```
Brcobranca::Retorno::Cnab400::Bradesco.load_lines(file)
```
