### ISSUE TITLE
Remessa inválida ao aplicar desconto

### ISSUE THREAD

**Issue by cassiopagnoncelli** [kivanio/brcobranca#188]
Olá caros,

Estou testando a feature de **desconto** do _brcobranca_ num sistema já existente e em produção. Tentei aplicar o **desconto fixo** para uma carteira de cobrança no Banco do Brasil,

```
Título: R$ 6,00
Desconto (até o vencimento): R$ 3,00
```

e preenchi três novos campos antes não preenchidos (nil): **cod_desconto**, **data_desconto** e **valor_desconto**.

```
Brcobranca::Remessa::Pagamento.new(
  valor: p.amount_billed,
  nosso_numero: p.boleto_seq,
  data_vencimento: p.due_date,
  documento_sacado: c.document.to_s.gsub(/\D/, ''),
  nome_sacado: c.simplified_name,
  endereco_sacado: address[:street],
  bairro_sacado: address[:district],
  cidade_sacado: address[:city],
  uf_sacado: address[:province],
  cep_sacado: address[:zipcode],

  # Desconto: novos campos.
  cod_desconto: 1,
  valor_desconto: 3.00,
  data_desconto: Date.current + 2
)
```

A remessa é gerada, mas o banco não aceita.

Algum aventureiro já teve este problema?

Obrigado!

**Comment by kivanio** [comment]
Não aceita por que?
Gerou mensagem de erro?
CNAB240 ou 400?

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2018-04-05 0:48 GMT-04:00 Cássio Jandir Pagnoncelli <
notifications@github.com>:

**Comment by cassiopagnoncelli** [comment]
Remessa CNAB240 para Banco do Brasil. Sim, gerou erro, dizia que a remessa não foi aceita, sem mais informações.

**Comment by cassiopagnoncelli** [comment]
Consegui replicar o problema e acho que encontrei o bug.

Numa remessa contendo 13 lotes, limitei os endereços a <40 caracteres (máximo para o CNAB240 é 40 caracteres para a rua e aparentemente o problema estava no trimming do endereço, onde ele coloca reticências quando o campo excede os 40 caracteres.

Foi de

<img width="738" alt="screen shot 2018-04-09 at 7 55 22 am" src="https://user-images.githubusercontent.com/4023526/38494408-3aa03d14-3bcc-11e8-9b07-142ce4f533af.png">

<img width="966" alt="screen shot 2018-04-09 at 7 55 31 am" src="https://user-images.githubusercontent.com/4023526/38494409-3ad84876-3bcc-11e8-823d-ea1cd3b729ef.png">

para registrado com sucesso.

**Comment by eternoscav** [comment]
Bom dia! Estou com um problema parecido porém no meu caso não aparece as "reticências" no endereço, Agradeço quem puder ajudar.
![image](https://user-images.githubusercontent.com/40268572/47431710-ed2a0e00-d772-11e8-927b-d7bd69cbfdcf.png)

Segue o Arquivo de Remessa

00100000         201069808000198001251997001417019  03041 00000011009630RANNIPLAST IND E COMERCIO ARTIBANCO DO BRASIL                         12410201809422400000005000000                                                                     
00100011R01  042 2001069808000198000000009001417019  0304100000001100963 RANNIPLAST IND E COMERCIO ARTI                                                                                000000002410201800000000                                 
0010001300001P 010304100000001100963 125199717 1251997000170191222000676         0910201800000000000030000000 01N09102018300000000000000000000000000000000000000000000000000000000000000000000000000000000676                   3000000090000000000 
0010001300002Q 012001069808000198RANNIPLAST IND E COMERCIO ARTIGOS PLASTIR AVIADOR MAX FONTOURA                  CENTRO INDUSTRI83413530COLOMBO        PR0000000000000000                                        000                            
00100015         00000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                                                             
00199999         000001000006000000

**Comment by kivanio** [comment]
Não vi nenhuma reticências no conteúdo da remessa que você enviou.
