### ISSUE TITLE
Boleto Vencido, reimpressão...

### ISSUE THREAD

**Issue by laerciocrestani** [kivanio/brcobranca#190]
Amigos boa tarde.

Hoje com o Boleto Registrado sabemos que o mesmo pode ser pago após o vencimento, porém pelo internet banking de alguns bancos não há ainda como pagar pelo aviso de "boleto vencido""

Quando adiciono ao valor do boleto valor + valor da multa + valor multa diaria, o valor fica correto.

Segue abaixo a imagem do boleto gerado pelo sistema usando o valor conforme o conceito acima. (valor + valor da multa + valor multa diaria) Sendo que o valor original é R$ 5,10, vencido dia 06/04

![captura de tela 2018-04-27 as 16 27 31](https://user-images.githubusercontent.com/1430869/39381271-f4505914-4a37-11e8-83d5-d415f0bb0277.png)

Porém não tenho como atribuir na impressão os valores de mora/juros conforme a imagem abaixo, boleto reimpresso pelo site da Caixa

![captura de tela 2018-04-27 as 16 29 52](https://user-images.githubusercontent.com/1430869/39381365-3f23b7d8-4a38-11e8-9086-d7ac227fc462.png)

Neste exemplo impresso direto do banco temos o valor do documento (fica original) mais a mora e juros e fica o valor cobrado corretamente conforme o código de barras.

Nesta gem não tenho como atribuir o valor do documento, mora e juros, alguém já passou por isso?

**Comment by marcelobarreto** [comment]
@laerciocrestani conseguiu resolver isso de alguma forma?

**Comment by laerciocrestani** [comment]
@marcelobarreto não consegui, fiz ajuste para mudar o valor do próprio boleto, mas se mudar a data de pagamento se a remessa for enviada vai pegar o valor antigo, gerando erro. Foi uma media paliativa mas não correta.

**Comment by gilcecler** [comment]
@laerciocrestani   Olá amiigo como esta fazendo com boletos vencidos na data atual.  
Exemplo no registro original do boleto:  **78810000125092**   / vencimento 06/05  valor 1250,92

A pessoa não pagou no vencimento e vai pagar em atraso.
Ela consegue pagar com o boleto original ?
No caso da reimpessão como voce esta fazendo?   voce muda o codigo de barras por exemplo para 125192  vamos imaginar o valor calculado de multa,  pois como foi registrado com outro valor, não sei se os bancos acertaram isso.
78810000125192   

Os meus clientes estão começando a pedir a reimpessão com valor calculado,  não se como fazer ainda.
abraço,

**Comment by kivanio** [comment]
Se você colocou e enviou multa, juros e tudo mais, não precisa reimprimir e
o cliente pode pagar vencido.
O banco vai calcular.
Não precisa fazer outro boleto.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/>

**Comment by gilcecler** [comment]
@laerciocrestani   Olá amiigo como esta fazendo com boletos vencidos.
Exemplo no registro original do boleto:  **78810000125092**   / vencimento 06/05  valor 1250,92

A pessoa não pagou no vencimento e vai pagar em atraso.
No caso da reimpessão como voce esta fazendo?   voce muda o codigo de barras por exemplo para 125192  para o valor calculado somando a multa
78810000125192   

abraço,

**Comment by gilcecler** [comment]
@kivanio   Obrigado  pela resposta.
Mas considere aquele cliente "exigente" para não falar outro nome, hehehe.   Que deseja imprimir após o vencimento com o juros e multa calculados.
É somente imprimir o mesmo boleto calculando juros e multa,  só para ver o calculo antes,  porque quando digitar para pagar como você disse já vai calcular.

**Comment by laerciocrestani** [comment]
Olá. Então, não fiz essa implementação. O Cliente paga diretamente o boleto e ele calcula com base nos valores de juro/mora que vc estabelece via remessa.
