### ISSUE TITLE
Geração de Arquivos de remessa

### ISSUE THREAD

**Issue by ademir10** [kivanio/brcobranca#199]
Boa tarde Kivanio tudo bem?
Me desculpe pela ignorância da minha parte, mais eu dei uma procurada e não encontrei documentação explicativa sobre a integração de Arquivos de remessa para o agendamento de pagamentos junto ao banco Itaú, você teria algum link que pudesse disponibilizar? Estou com a necessidade de geração deste arquivo para o Itaú.
Se você puder disponibilizar algum link de exemplo ei ficaria agradecido, muito obrigado.

**Comment by ademir10** [comment]
Boa tarde pessoal, alguém saberia dizer se existe esta possibilidade? gerar um DDA de remessa para o banco itáu?
O cliente já possui um contas a pagar, ai nesse caso eu só extrairia as informações necessárias de cada conta a pagar e geraria o arquivo de remessa solicitando ao banco que realize os pagamentos..
Estou precisando fazer isso porém não sei se esta Gem possui também este recurso..
Se puderem disponibilizar o link da documentação sobre isso eu agradeceria, obrigado.

**Comment by kivanio** [comment]
A gem que você quer é essa:
https://github.com/eduardordm/cnab240

**Comment by marcelsavegnago** [comment]
@ademir10 vc chegou a utilizar esta gem citada pelo @kivanio ?

**Comment by ademir10** [comment]
> @ademir10 vc chegou a utilizar esta gem citada pelo @kivanio ? Estou pesquisando algo que possa atender outros bancos também além do Itaú

Não cheguei a fazer a implementação, na época o cliente acabou dando uma segurada e não avançamos.

**Comment by kivanio** [comment]
@marcelsavegnago não tem outra gem pública até onde eu conheço.
Somente essa cnab240.

A `brcobranca` só faz remessa de boletos de cobrança.
E você está procurando para remessa de pagamentos/transferências, certo?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago não tem outra gem pública até onde eu conheço. Somente essa cnab240.
> 
> A `brcobranca` só faz remessa de boletos de cobrança. E você está procurando para remessa de pagamentos/transferências, certo?

Boa tarde @kivanio. Sim estou procurando algo para remessa de pagamentos/transferencia.

**Comment by rvalyi** [comment]
(@kivanio o @marcelsavegnago é mais um que ta vindo ao brcobranca a partir da comunidade do Odoo ERP/OCA do Brasil e do API REST brcobranca que fizemos https://github.com/akretion/boleto_cnab_api  So que realmente avisei ele que o foco aqui era so boletos de cobrança.)

**Comment by kivanio** [comment]
Eu aceitaria um PR sobre isso.

Eu não estou fazendo isso, então não tenho o porque fazer na gem.

Mas se alguém se habilitar a contribuir, está aprovado :D
Eu até ajudo com documentações e dicas, pois tenho um pouco do conhecimento.

Mas a realidade atual é usar as APIs de open banking do banco.
Arquivos CNABs vão cair em desuso logo logo.
