### ISSUE TITLE
Logo Safra muito grande

### ISSUE THREAD

**Issue by GianMantuan** [kivanio/brcobranca#201]
Após gerar um boleto do Banco Safra, a logo quebrou uma parte do boleto. 
Baixando o .eps, em comparação com a logo do itau, verifiquei que a imagem está muito maior que o esperado.
![boleto-safra](https://user-images.githubusercontent.com/28939811/47432951-c7eacf00-d775-11e8-900a-7e0a96d5bba5.jpg)

**Comment by kivanio** [comment]
Pode mandar um patch com correção?

**Comment by GianMantuan** [comment]
Eu não possuo nenhum ambiente configurado para teste ou desconheço como criar uma build desse projeto, se puder me dar um caminho, eu consigo fazer as alterações, desculpe a novatice, primeira vez fazendo isso
