### ISSUE TITLE
Endereço do Sacado

### ISSUE THREAD

**Issue by heliortf** [kivanio/brcobranca#210]
Olá @kivanio e contribuidores!

parabéns pelo projeto e pelo esmero em manter o code coverage sempre alto.

Tenho uma dúvida.. hoje na geração de boletos o endereço do sacado segue em uma linha só e  nos casos onde o boleto vai num envelope com janela pequena, não é exibido todo o endereço.

https://github.com/kivanio/brcobranca/blob/a5ad29a72bc0ea0fe0b8f60187b25fe331d6e8a0/lib/brcobranca/boleto/template/rghost.rb#L186

Se essa exibição fosse talvez usando doc.text poderia ser possível quebrar a linha do endereço

https://github.com/shairontoledo/rghost/wiki/Printing-text

Vocês aceitariam uma contribuição assim ou poderiam fazer essa alteração no projeto? Caso queira contribuir como procedo?

Desde já, agradeço.

Abraço!

**Comment by kivanio** [comment]
O melhor seria fazer um novo layout envelope.

É só enviar um PR! \o/

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/>
