### ISSUE TITLE
Erro ao executar o send_data

### ISSUE THREAD

**Issue by andresulivam** [kivanio/brcobranca#213]
Olá!
Usando o mesmo código do projeto de exemplo ocorre o seguinte erro:

`RGhost::RenderException at /dependent_bills
Error: /invalidfileaccess in --run--
 Operand stack:
    (/Users/andresulivam/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/brcobranca-9.2.4/lib/brcobranca/boleto/template/../../arquivos/templates/modelo_generico.eps)   (r)
 Execution stack:
    %interp_exit   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   run   false   1   %stopped_push   1974   1   3   %oparray_pop   1973   1   3   %oparray_pop   1961   1   3   %oparray_pop   1817   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   1974   1   3   %oparray_pop   run
 Dictionary stack:
    --dict:738/1123(ro)(G)--   --dict:0/20(G)--   --dict:244/300(L)--
 Current allocation mode is local
 Last OS error: Permission denied
 Current file position is 4172`

Segue o código executado:

`
boleto_dados = { :cedente => "Kivanio Barbosa",
      :documento_cedente => "12345678912",
      :sacado => "Claudio Pozzebom",
      :sacado_documento => "12345678900",
      :valor => 135.00,
      :agencia => "4042",
      :conta_corrente => "61900",
      :convenio => "1238798",
      :nosso_numero => "7777700168",
      :data_vencimento => "2008-02-01".to_date,
      :data_documento => "2008-02-01".to_date,
      :instrucao1 => "Pagável na rede bancária até a data de vencimento.",
      :instrucao2 => "Juros de mora de 2.0% mensal(R$ 0,09 ao dia)",
      :instrucao3 => "DESCONTO DE R$ 29,50 APÓS 05/11/2006 ATÉ 15/11/2006",
      :instrucao4 => "NÃO RECEBER APÓS 15/11/2006",
      :instrucao5 => "Após vencimento pagável somente nas agências do Banco do Brasil",
      :instrucao6 => "ACRESCER R$ 4,00 REFERENTE AO BOLETO BANCÁRIO",
      :sacado_endereco => "Av. Rubéns de Mendonça, 157 - 78008-000 - Cuiabá/MT" 
    }

    @boletos = []
    @boleto = Brcobranca::Boleto::BancoBrasil.new(boleto_dados)
    @boleto2 = Brcobranca::Boleto::Bradesco.new(boleto_dados)
    @boletos << @boleto
    @boletos << @boleto2

    send_data Brcobranca::Boleto::Base.lote(@boletos), :filename => "multi_boleto.pdf"`

Uma situação que reparei que sempre se instala a versão 9.2.4. Mesmo eu colocando manualmente para instalar uma outra versão.
Já executei em diversas versões do ruby como do rails e o erro sempre permance.

Obrigado pelo apoio!

**Comment by andresulivam** [comment]
Era probelma de versão do ghostscript.
Precisei realizar um downgrade de versão para a 9.18.
Utilizo MacOS.

**Comment by kivanio** [comment]
bom saber!

Precisamos migrar para algo como o prawn.

**Comment by andresulivam** [comment]
> bom saber!
> 
> Precisamos migrar para algo como o prawn.

Bacana!
Já trabalhei em uns 2 projetos utilizando o prawn. 
Vou me programar pra separar um tempo e verificar se consigo ajudar nesse ponto.
Valeu!

**Comment by kivanio** [comment]
Se enviar um PR aceito na hora \o/

Kivanio
