### ISSUE TITLE
Código de barras inválido

### ISSUE THREAD

**Issue by jhonytaveira** [kivanio/brcobranca#221]
Estou gerando o código de barras manualmente através desse método **codigo_barras** porém está gerando um código inválido, com isso não se consegue efetuar um pagamento. Alguém consegue me ajudar? estou fazendo algo errado?

Observação: No boleto funciona normalmente. 

Obrigado

**Comment by kivanio** [comment]
Está dando erro ao gerar ou erro ao pagar?
Erro ao: Dados errados para a geração
Erro ao pagar: Falta registrar o boleto no banco.

**Comment by jhonytaveira** [comment]
Resolvi utilizando o método **linha_digitavel**
Valeu
