### ISSUE TITLE
Santander 400 gerando código de barras incorreto

### ISSUE THREAD

**Issue by viny-dc** [kivanio/brcobranca#224]
Prezados gostaria de agradecer a belíssima gem desenvolvida por vocês, porém com o ponto de atenção a seguir:
Através da solução santander.rb temos o retorno correto do código de barras somente para o CNAB 240 ao realizar a função modulo11 para o CNAB400 o código de barras gerado fica de forma incorreto. Uma vez que o CNAB 400 não tem a necessidade do calculo do dv. Sabemos que a própria documentação informa a necessidade do calculo, porém testando com alguns cnabs tínhamos sempre o retorno do digito verificador como 0, desta forma acreditamos que não exista a necessidade do calculo. Segue em anexo a documentação mais atual que consegui.
[Manual Santander 400.pdf](https://github.com/kivanio/brcobranca/files/7205755/Manual.Santander.400.pdf)

**Comment by kivanio** [comment]
Os CNABs não geram código de barras.
Não entendi o seu ponto.
Na geração do boleto deve enviar o nosso número COM dígito.
