### ISSUE TITLE
Conta Cosmos - Citibank

### ISSUE THREAD

**Issue by Josebr1** [kivanio/brcobranca#225]
**### Citibank**

Alguem sabe ou pode me ajudar a identificar a conta cosmos no arquivo remessa/retorno (as posições no header)?

Ele fica no header (código da empresa), so que esse campo tem 20 posições, sei que as ultimas 3 são referentes ao portifolio, mas a conta cosmos eu não sei

**Comment by kivanio** [comment]
@Josebr1 não vem ela inteira.
Vem um pedaço na posição 26, 6 caracter e outro pedaço na posição 43, 3 caracter.
