### ISSUE TITLE
RGhost::RenderException: Error: /invalidfileaccess in --run--

### ISSUE THREAD

**Issue by PedroPauloML** [kivanio/brcobranca#229]
Olá, pessoal. 

Estou recebendo o seguinte problema na geração do PDF.

```sh
RGhost::RenderException: Error: /invalidfileaccess in --run--
 Operand stack:
    (/Users/pedropaulomarquesdelima/.rvm/gems/ruby-2.7.2/gems/brcobranca-9.2.4/lib/brcobranca/boleto/template/../../arquivos/templates/modelo_generico.eps)   (r)
 Execution stack:
    %interp_exit   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   run   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1977   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   run   --nostringval--   2   %stopped_push   --nostringval--   run   1990   1   3   %oparray_pop   run
 Dictionary stack:
    --dict:732/1123(ro)(G)--   --dict:0/20(G)--   --dict:244/300(L)--
 Current allocation mode is local
 Last OS error: Permission denied
 Current file position is 3917

from /Users/pedropaulomarquesdelima/.rvm/gems/ruby-2.7.2/gems/rghost-0.9.7/lib/rghost/ruby_ghost_engine.rb:88:in `render'
```

Poderiam me ajudar com esse problema?

**Comment by kivanio** [comment]
Resolvido no master

**Comment by brunoarueira** [comment]
@kivanio bom dia, primeiro agradecer pela excelente gem 😄 Seria possível gerar uma nova release? Estou encontrando problema similar no projeto que atuo e ao apontar para a master, os testes estão passando e com a última versão do rubygems não.

**Comment by kivanio** [comment]
@brunoarueira feito 👌🏻

**Comment by PedroPauloML** [comment]
> @kivanio bom dia, primeiro agradecer pela excelente gem 😄 Seria possível gerar uma nova release? Estou encontrando problema similar no projeto que atuo e ao apontar para a master, os testes estão passando e com a última versão do rubygems não.

Muito obrigado, @brunoarueira, era exatamente esse o meu problema kkk
