### ISSUE TITLE
Tamanho do Nosso Numero BB

### ISSUE THREAD

**Issue by brunno-souza-esl** [kivanio/brcobranca#230]
https://www.bb.com.br/docs/pub/emp/empl/dwn/Doc5175Bloqueto.pdf

Segundo a documentação do BB, quando o convênio possui 7 posições o nosso número possui tamanho 17.

Segue print:

![image](https://user-images.githubusercontent.com/86249390/154498562-be7990a4-6f99-4f2f-a295-977c36d65654.png)

**Comment by brunno-souza-esl** [comment]
Fiz a correção no meu fork, assim que possível faço o PR para o repo principal.

**Comment by netosjb** [comment]
quando vc for fazer a pr ai é interessante já atualizar o arquivo do manual que a versão que tem no repositório é de 2016

**Comment by brunno-souza-esl** [comment]
Fiz um novo estudo da documentação e do problema descrito pelo meu cliente, e a gem está correta. O problema é que meu cliente está enviando o código do convênio junto com o nosso número.
Como descrito pela própria documentação do BB é um campo de 17 posições que possui o convênio + o nosso número.

Vou fechar o problema.
