### ISSUE TITLE
permitir usar prawn

### ISSUE THREAD

**Issue by eduardordm** [kivanio/brcobranca#58]
Bom dia amigos!

Será que não seria interessante que a geração do boleto fosse feita em ruby? Em minha empresa usamos o prawn para gerar notas fiscais e funciona muito bem.

Não sei se facilitaria o desenvolvimento, mas o deploy ficaria bem mais fácil uma vez que prawn é escrita em ruby.

O que acham?

**Comment by gabpaladino** [comment]
Fiz um comentário agora no #6 sobre um fork que está trabalhando com layouts HTML para quem quiser o que torna bem simples customizar por aplicação e também estamos convertendo para PDF com wkhtmltopdf + wicked_pdf.. Não sei o que acham da abordagem mas a questão de ser HTML facilita bastante aqui para customizar os layouts e colocar umas besteiras..

**Comment by eduardordm** [comment]
Oi @gabpaladino já testaram com bastante volume? Eu tenho tido bastante problemas de memória com wkhtmltopdf, isso desde a versão 2 do ruby. Não sabemos o que aconteceu mas como usamos essa parte com sidekiq, acabou que só aumentamos a memória dos servidores de batch.

Eu comecei a implementar algo pra fazer um PR mas duas filhas dão mais trabalho do que eu imaginava. :D

**Comment by gabpaladino** [comment]
Oi @eduardordm, obrigado pela informação, ainda não tivemos volume para avaliar isso, mas assim já fico esperto para acompanhar se tiver algum problema. Pelo menos, tendo o HTML se der problema também é só desativar o pdf.

**Comment by kivanio** [comment]
Também tenho problemas de memória :/

Kivanio Barbosa


2015-09-09 7:55 GMT-04:00 Gabriel Paladino <notifications@github.com>:

**Comment by gabpaladino** [comment]
Para tentar estabelecer um parâmetro, de que volume e quantidade de memória vocês estão falando?

**Comment by brodock** [comment]
eu tive muitos problemas com o wkhtmltopdf anteriormente, talvez traga mais problema que solução.

**Comment by eduardordm** [comment]
Umas 100 paginas de PDF apenas com texto ocupou 5GB de ram em um caso. Isso começou no Ruby 2. Com 1.9 não tem esse problema, tem cara de ser algo com subshell talvez? Dá pra usar o DTrace pra descobrir, se alguém tiver mais tempo: 

```d
ruby*:::object-create
{
  @objects[copyinstr(arg0)] = count();
}
```
