### ISSUE TITLE
Exportar pra HTML

### ISSUE THREAD

**Issue by elomar** [kivanio/brcobranca#6]
Tem como renderizar o boleto em HTML mesmo, tipo esse [http://www.boletophp.com.br/boletophp/boleto_cef.php]? 

A gente passou por uns problemas exportando pra PDF, com gente que não tinha o acrobat e o send_data travando o servidor. Exportar pra HTML seria uma boa :)

**Comment by gabpaladino** [comment]
Oi pessoal, deletei esse fork antigo que que tinha sido feito para montar templates em html e estava com outro nome perdendo a compatibilidade com a gem original e refizemos a lógica de html que também é exportável para PDF através do wkhtmltopdf + wicked_pdf..

Acabei de subir em https://github.com/scupen/brcobranca/tree/modelo_carne_html

Não sei faz sentido um pull request e se é a melhor forma de lidar com a questão do template, mas é a forma como funciona melhor para a gente. Acho mais fácil e também é simples de personalizar de acordo com cada aplicação. Nesse caso usamos da seguinte forma:

```ruby
render Brcobranca::Boleto::BancoBrasil.new(params).layout() # para html
render Brcobranca::Boleto::BancoBrasil.new(params).layout(pdf: 'nome-arquivo') # para pdf

render Brcobranca::Boleto::Base.layout(boletos: [], modelo: 'carne') # para carne html
render Brcobranca::Boleto::Base.layout(boletos: [], modelo: 'carne', pdf: 'nome-arquivo') # para carne pdf
```
