### ISSUE TITLE
"Nosso número" Santander com limite de 8 dígitos

### ISSUE THREAD

**Issue by wagner** [kivanio/brcobranca#76]
Porque o "nosso número" continua limitado a 8 dígitos? A documentação diz que, exceto para os bancos  353 e 008 (antigos códigos do Santander), o n/n deveria ter 12 dígitos. Na minha opinião não faz sentido ter essa limitação se o código do banco está fixo em 033 (que suporta os 12).

Existe algum outro motivo que não entendi?

**Comment by plentz** [comment]
@wagner pode mandar um PR com a alteração :) será bem vindo

**Comment by ronyvieira** [comment]
Estou tendo esse problema no Itaú também. Via bankline consigo gerar número do documento com 10 dígitos (não testei número maiores)  e na gem há essa validação de 8.

**Comment by guialbuk** [comment]
Eu também uso Itaú. Antes realmente ele só aceitava até 8 dígitos no nosso número. Agora eles estão aceitando até 10 nos sistemas do Internet Banking.

**Comment by kivanio** [comment]
É por causa da Remessa que só aceita 8 ;)
Os limites estão de acordo a Remessa, 
ou daria um problemão permitir mais que o limite da remessa.
Caso a remessa mude, mudamos o limite.
Abraço.
