### ISSUE TITLE
Formato Carnê - Logotipo CAIXA muito Grande

### ISSUE THREAD

**Issue by danieldenis01** [kivanio/brcobranca#80]
Ao gerar os boletos da CAIXA em Formato Carnê, o Logotipo do Banco ocupa espaço maior do que o reservado, na versão 4.0.0

**Comment by plentz** [comment]
pode enviar um boleto gerado da caixa?

**Comment by danieldenis01** [comment]
![captura de tela 2015-04-16 as 00 00 57](https://cloud.githubusercontent.com/assets/1375216/7173337/f20ccc26-e3cb-11e4-8137-731e4e82b51d.png)

**Comment by oliveiradev** [comment]
@danieldenis01 um carnê que gerei do BB também ficou assim , estou usando o module
```ruby
Brcobranca::Boleto::Template::RghostCarne

```

**Comment by guialbuk** [comment]
@oliveiradev   O do BB também ficou com o logo grande e duplicado?
Você poderia manda uma imagem?
Vou gerar alguns testes aqui para resolver isso.

**Comment by oliveiradev** [comment]
![screenshot from 2015-10-07 14 23 33](https://cloud.githubusercontent.com/assets/5739331/10345301/12e94a66-6cff-11e5-87f3-813141d8c883.png)

**Comment by guialbuk** [comment]
Legal. Já consegui reproduzir o bug.
Vou fazer um ajuste fino nos logotipos e no posicionamento deles para boletos comuns e carnês.

**Comment by lucasmncastro** [comment]
Oi Pessoal,

Estou usando a versão 6.4.1 e estou tendo esse mesmo problema com o banco do brasil.
Estou usando o método:  Brcobranca::Boleto::Template::RghostCarne.lote_carne

Alguma sugestão do que pode ser?

**Comment by lucasmncastro** [comment]
Consegui resolver, mas tive que adicionar esse código antes de gerar o carnê:
`Brcobranca.configuration.gerador = :rghost_carne`

E antes de gerar no modo boleto, altero para:
`Brcobranca.configuration.gerador = :normal`

Na verdade o :normal poderia ser qualquer coisa diferente de :rghost_carne.

Se houver alguma forma mais adequada, me avisem! ;)

**Comment by LenineNobrega** [comment]
Amigos uma ajuda, o brcobranca permite alternar de rghost para rghost_carne em tempo de execução ?
