### ISSUE TITLE
Posição do cedente (Sem endereço)

### ISSUE THREAD

**Issue by brunorails** [kivanio/brcobranca#83]
https://github.com/kivanio/brcobranca/commit/db34a0e53b126626c491520f7d0df05b4b28dc2b#diff-c7d46d015ec10d72922097f0cca7f348L177

```ruby
doc.moveto x: '1.9 cm', y: '15.5 cm'
doc.show boleto.cedente
doc.moveto x: '0.7 cm', y: '15.2 cm'
doc.show boleto.cedente_endereco
```

O novo atributo 'cedente_endereco' alterou o local do 'cedente'. Mas quando não tem o endereço, da impressão de estar no lugar errado.

Acho que o correto, seria ficar assim:

```ruby
doc.moveto x: '0.7 cm', y: '15.2 cm'
if boleto.cedente_endereco
  doc.show boleto.cedente_endereco
  doc.moveto x: '1.9 cm', y: '15.5 cm'
  doc.show boleto.cedente
else
  doc.show boleto.cedente
end
```

**Comment by kivanio** [comment]
Show, tem como mandar um patch?

**Comment by brunorails** [comment]
:+1:
