### ISSUE TITLE
Problemas com geração de boleto em qualquer formato

### ISSUE THREAD

**Issue by zehpavora** [kivanio/brcobranca#85]
Olá.

Estou usando a Gem de vocês e estou com um problema para geração em qualquer formato (PDF, PNG, TIFF, ...).

Ao executar o comando para gravação presente até nos exemplos:
```
boleto.to(:pdf)
```

Meu código falha, resultando no seguinte Stacktrace:

``` ruby
Error: /undefinedresource in resourcestatus Operand stack: false ct_StyleDicts --dict:0/4(L)-- Adobe-Japan1 --dict:0/4(L)-- Serif HeiseiMin-W3-83pv-RKSJ-H Font HeiseiMin-W3 CIDFont Execution stack: %interp_exit .runexec2 --nostringval-- --nostringval-- --nostringval-- 2 %stopped_push --nostringval-- --nostringval-- --nostringval-- false 1 %stopped_push 1967 1 3 %oparray_pop 1966 1 3 %oparray_pop 1950 1 3 %oparray_pop 1836 1 3 %oparray_pop --nostringval-- %errorexec_pop .runexec2 --nostringval-- --nostringval-- --nostringval-- 2 %stopped_push --nostringval-- --nostringval-- 1967 1 3 %oparray_pop 1967 1 3 %oparray_pop 1966 1 3 %oparray_pop --nostringval-- 1950 1 3 %oparray_pop 1836 1 3 %oparray_pop --nostringval-- %errorexec_pop .runexec2 --nostringval-- --nostringval-- --nostringval-- 2 %stopped_push --nostringval-- --nostringval-- --nostringval-- 1915 10 9 %oparray_pop Dictionary stack: --dict:1186/1684(ro)(G)-- --dict:0/20(G)-- --dict:255/300(L)-- --dict:57/75(L)-- --dict:2/10(L)-- --dict:39/70(L)-- --dict:0/4(L)-- --dict:0/4(L)-- --dict:20/27(ro)(G)-- --dict:20/26(ro)(G)-- Current allocation mode is local Last OS error: No such file or directory 
```
Depois de muito buscar na internet, consegui a char a seguinte configuração:
```
Brcobranca.setup do |config|
  config.external_encoding = 'ascii-8bit'
end
```

Mas que não resolveu meu problema.

Seguindo detalhes do Stack, cheguei nos seguintes arquivos:
```
rghost (0.9.5) lib/rghost/ruby_ghost_engine.rb:86:in `render'
rghost (0.9.5) lib/rghost/document.rb:238:in `render'
rghost (0.9.5) lib/rghost/document.rb:258:in `render_stream'
brcobranca (4.1.0) lib/brcobranca/boleto/template/rghost.rb:87:in `modelo_generico'
brcobranca (4.1.0) lib/brcobranca/boleto/template/rghost.rb:34:in `to'
```

Estudei os seguintes arquivos e rodei testes usando apenas a gem do RGhost e não consegui reproduzir.

Dessa forma, entendo que o problema está relacionado, de alguma forma, a Gem de Brcobranca.

Não consegui chegar a um maior nível de detalhe mas acho que tem algo haver com o arquivo de formato, o template **modelo_generico.eps**.

Obrigado.

**Comment by kivanio** [comment]
Acho que o seu ghostscript é muito antigo.
Tentei atualizar ele

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2015-05-12 16:46 GMT-04:00 zehpavora <notifications@github.com>:

**Comment by zehpavora** [comment]
@kivanio,

Tentei atualizar e recebi essa mensagem do APT-GET:
```
sudo apt-get install ghostscript
ghostscript is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by kivanio** [comment]
Qual é sua versão?

A minha:

gs --version
                                            9.16


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by zehpavora** [comment]
@kivanio,

A minha apareceu como 9.15 no Ubuntu.
Estou vendo como faço para atualizar.

**Comment by kivanio** [comment]
Sendo 9.x não deve ter problema.

Deve ser alguma outra coisa.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by kivanio** [comment]
Teste com esse código para tirar a dúvida se é algo no seu app ou no
ambiente:
https://github.com/kivanio/brcobranca_exemplo

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2015-05-13 9:49 GMT-04:00 Kivanio Barbosa <kivanio@gmail.com>:

**Comment by zehpavora** [comment]
@kivanio,

Testei aqui e apresentou o mesmo erro.
Você tem laguma ideia sobre dependências do GS?

Estou validando se isso não pode ser um problema.

**Comment by kivanio** [comment]
Geralmente ele instala tudo, não lembro de nada específico de dependência.

Já tentou remover e instalar novamente?
Já tentou passar o local onde ele está instalado para a gem? (which gs)


Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2015-05-13 10:04 GMT-04:00 zehpavora <notifications@github.com>:

**Comment by zehpavora** [comment]
@kivanio,

 o comando which() retornou:
```
/usr/bin/gs
```

Entendo que está correto.
Vou fazer a reinstalação do mesmo, mas acho que este não é o problema pois os comandos básicos de RGhost rodam a partir do console.

Como e u faço para configurar o Path diretamente na Gem?

Obrigado pela ajuda!

**Comment by zehpavora** [comment]
@kivanio,

Ainda não consegui resolver o problema, alguma luz?

**Comment by JaeggerFrank** [comment]
Boa noite
Estou com o mesmo problema. Consegui clonar o repositório, executar bundle install e até abrir a home page da aplicação, porém, quando seleciono qualquer boleto de qualquer banco para geração em qualquer formato recebo o seguinte erro(No navegador):

Error: /undefinedresource in resourcestatus Operand stack: false ct_StyleDicts --dict:0/4(L)-- Adobe-Japan1 --dict:0/4(L)-- Serif HeiseiMin-W3-83pv-RKSJ-H Font HeiseiMin-W3 CIDFont Execution stack: %interp_exit .runexec2 --nostringval-- --nostringval-- --nostringval-- 2 %stopped_push --nostringval-- --nostringval-- --nostringval-- false 1 %stopped_push 1967 1 3 %oparray_pop 1966 1 3 %oparray_pop 1950 1 3 %oparray_pop 1836 1 3 %oparray_pop --nostringval-- %errorexec_pop .runexec2 --nostringval-- --nostringval-- --nostringval-- 2 %stopped_push --nostringval-- --nostringval-- 1967 1 3 %oparray_pop 1967 1 3 %oparray_pop 1966 1 3 %oparray_pop --nostringval-- 1950 1 3 %oparray_pop 1836 1 3 %oparray_pop --nostringval-- %errorexec_pop .runexec2 --nostringval-- --nostringval-- --nostringval-- 2 %stopped_push --nostringval-- --nostringval-- --nostringval-- 1915 10 9 %oparray_pop Dictionary stack: --dict:1186/1684(ro)(G)-- --dict:0/20(G)-- --dict:255/300(L)-- --dict:57/75(L)-- --dict:2/10(L)-- --dict:39/70(L)-- --dict:0/4(L)-- --dict:0/4(L)-- --dict:20/27(ro)(G)-- --dict:20/26(ro)(G)-- Current allocation mode is local Last OS error: No such file or directory 

O erro ocorre na linha 82 do arquivo app/controllers/home_controller.rb
    formato=params[:boleto][:formato].to_sym
    headers['Content-Type']=FORMATOS_SUPORTADOS[formato]
    send_data @boleto.to(formato), :filename => "boleto_#{banco}.#{formato}"
  end

PORÉM, no console , o erro que aparece é diferente
Parameters: {"utf8"=>"✓", "authenticity_token"=>"NWIeWxorE/XH5gj7bvn9Z590lcm8nc1XnY6s5sxWB1xm0k7N4w3OM6mxSQM8asPcT8kFkoYEHmR2gRfFjHVrKw==", "boleto"=>{"formato"=>"pdf"}, "commit"=>"Gerar", "banco"=>"bb"}
GPL Ghostscript 9.15: Unrecoverable error, exit code 1
Completed 500 Internal Server Error in 623ms

RGhost::RenderException (Error: /undefinedresource in resourcestatus
 Operand stack:
    false   ct_StyleDicts   --dict:0/4(L)--   Adobe-Japan1   --dict:0/4(L)--   Serif   HeiseiMin-W3-83pv-RKSJ-H   Font   HeiseiMin-W3   CIDFont
 Execution stack:
    %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1967   1   3   %oparray_pop   1966   1   3   %oparray_pop   1950   1   3   %oparray_pop   1836   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   1967   1   3   %oparray_pop   1967   1   3   %oparray_pop   1966   1   3   %oparray_pop   --nostringval--   1950   1   3   %oparray_pop   1836   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1915   10   9   %oparray_pop
 Dictionary stack:
    --dict:1186/1684(ro)(G)--   --dict:0/20(G)--   --dict:255/300(L)--   --dict:57/75(L)--   --dict:2/10(L)--   --dict:39/70(L)--   --dict:0/4(L)--   --dict:0/4(L)--   --dict:20/27(ro)(G)--   --dict:20/26(ro)(G)--
 Current allocation mode is local
 Last OS error: No such file or directory
):
  app/controllers/home_controller.rb:82:in `gerar_boleto'


Aparentemente no Ghostscript que está o erro.Procurei em vários locais da internet , porém nenhuma resposta. Até havia enviado um email para o Kivanio pedindo por instruções e ele pediu pra baixar o exemplo e trabalhar a partir dele.

Segue meu ambiente:
So: ubuntu 15.04 x64 (Atualizado) com o ambiente padrão Gnome
Rails: 4.2,1
Ruby: ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
Ghostscript:
 GPL Ghostscript 9.15 (2014-09-22)
Copyright (C) 2014 Artifex Software, Inc.  All rights reserved.


Passos que realizei até esse erro:
Dentro do ambiente descrito acima:
1 - Clonei o repositório -> Git clone https://github.com/kivanio/brcobranca_exemplo
2- Executei bundle install (Instalação das Gems sem erro nenhum)
3- Executei o comando rails s pra iniciar o servidor
4-Abri a aplicação na porta padrão: http://localhost:3000

Consigo visualizar a aplicação como no exemplo https://brcobranca.herokuapp.com, porém na hora de gerar qualquer boleto, o erro ocorre.

Uma dúvida que fique é a seguinte: No endereço https://github.com/kivanio/brcobranca estão duas pastas, Lib  e Spec, cujo conteúdo , não é o mesmo da aplicação de exemplo em https://github.com/kivanio/brcobranca_exemplo . Até fiz um teste , copiando o conteúdo de lib e spec pra dentro da aplicação de exemplo. Não resolveu o problema, porém o erro (send_data @boleto.to(formato), :filename => "boleto_#{banco}.#{formato}" ) muda para outro e fica o seguinte:

          formato = (options.delete(:formato) || Brcobranca.configuration.formato)
          resolucao = (options.delete(:resolucao) || Brcobranca.configuration.resolucao)
          doc.render_stream(formato.to_sym, resolution: resolucao)
        end
        # Retorna um stream para multiplos boletos pronto para gravação em arquivo.

Nos arquivos:
lib/brcobranca/boleto/template/rghost.rb:87:in `modelo_generico'
lib/brcobranca/boleto/template/rghost.rb:34:in `to'
app/controllers/home_controller.rb:82:in `gerar_boleto'

E no console o MESMO erro no Ghostscript ocorre: GPL Ghostscript 9.15: Unrecoverable error, exit code 1

O mais pŕoximo que cheguei de uma possível solução foi que é um erro de fonte ou codifcação (Adobe-Japan1 --dict:0/4(L)-- Serif HeiseiMin-W3-83pv-RKSJ-H Font HeiseiMin-W3) ou que essa fonte não está presente no S.O. Mas ficou por isso mesmo e não encontrei mais nada relativo ao problema.

 A outra dúvida é que , após executar bundle install, não consigo executar o rake db:create ou rake db:migrate: Ocorrendo o seguinte erro:
rake aborted!
Don't know how to build task 'db:create

Tenho outras aplicações em desenvolvimento no mesmo computator , e não tenho esse problema com elas.

Creio que deve ser algo bem banal , como conflito entre a gem brcobranca e alguma outra coisa. Essa é uma Gem que quero continuar a trabalhar com ela por bastante tempo, por já ter o arquivo de retorno para os principais bancos e por gerar um boleto impecável.

**Comment by kivanio** [comment]
Tente reinstalar o Ghostscript, possivelmente é um problema na instalação
dele ou de dependências.

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2015-06-22 23:59 GMT-04:00 Pedro Paulino <notifications@github.com>:

**Comment by JaeggerFrank** [comment]
Re-instalar a Gem ou mesmo o Ghostscript em si não resolveram.

Alguma outra idéia ?

**Comment by kivanio** [comment]
Não é a primeira vez que vejo alguém com esse problema no Ubuntu.
Acho que tem algo errado com o ghostscript no Ubuntu.

Tente instalar outra versão mais antiga ou uma mais nova.
Com certeza o problema é no ghostscript

Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

**Comment by zehpavora** [comment]
Pessoal,

Aqui no escritório existem pessoas com Ubuntu que conseguiram fazer a geração de primeira.

Eu, por outros motivos, tive que reinstalar o Ubuntu na minha máquina e mesmo assim não consigo gerar os PDFs.

Sei que o código funciona pois nos nossos servidores bem como outras máquinas de DEV estão OK.

Gostaria de saber se vocês tem conhecimento de uma validação para a instalação do Ghostscript.

**Comment by kivanio** [comment]
Será que não falta alguma dependência?
Na teoria ele deveria instalar tudo o que for necessário de primeira.

Bem estranho isso.



Kivanio Barbosa
*boletosimples* Profissionalize sua cobrança com boleto bancário!
BoletoSimples.com.br <http://boletosimples.com.br/> | CobreGratis.com.br
<http://cobregratis.com.br/>

2015-06-24 9:05 GMT-04:00 zehpavora <notifications@github.com>:

**Comment by JaeggerFrank** [comment]
Bom, é uma possibilidade
Mas após clonar o exemplo e executar bundle install, ele baixa tudo sem erro algum

Irei instalar essa versão do Ghostscript para testes.

ghostscript_9.10~dfsg-0ubuntu10_amd64.deb

**Comment by JaeggerFrank** [comment]
Realmente não funcionou.

Verifiquei todas as dependências e a única que precisou de um upgrade foi uma dependência do Pearl, porém não resolveu também.

**Comment by zehpavora** [comment]
@JaeggerFrank:
Você tentou usar o aptitude no lugar do apt-get?

Tive problemas com outros softwares e o aptitude ajudou.
Ainda não tive a chance de usa-lo neste problema mas assim que encontrar um tempo, tentarei.

**Comment by JaeggerFrank** [comment]
@zehpavora  acabei de testar e realmente não funcionou.

Tenho um desktop onde instalei o Debian 8 (jessie x64) pra fazer uns testes  e o erro persiste.

**Comment by JaeggerFrank** [comment]
@zehpavora você conseguiu fazer sua aplicação funcionar ?

**Comment by zehpavora** [comment]
@JaeggerFrank ainda não, vou usar o aptitude para reinstalar o GS e suas dependências.

**Comment by JaeggerFrank** [comment]
ATUALIZAÇÃO: O problema é um conlito entre a versão 9.15 do Ghostscript com a Versão 15.x.x do Ubuntu. 

Segue o link do bug: http://www.mail-archive.com/desktop-packages@lists.launchpad.net/msg389708.html

Como resolvi o problema: Criei um ambiente de desenvolvimento no Ubuntu 14.04 x64 e tudo funciona perfeitamente,Emiti vários boletos em diferentes formatos.

Visto o link acima , creio que será necessário aguardar um patch pra uma versão do ubuntu, ou no meu caso, como estou com pressa, fazer um downgrade no ambiente pra que tudo funcione perfeitamente

**Comment by kivanio** [comment]
Obrigado @JaeggerFrank

**Comment by Ronair** [comment]
Consegui resolver este problema no ubuntu 15.04 instalando este pacote:
$ sudo apt-get install texlive-lang-cjk

**Comment by kivanio** [comment]
nive +1

**Comment by josuetex** [comment]
@Ronair esse pacote tem 1,6 GB ?

**Comment by josuetex** [comment]
Com esse parâmetro a mais cai para 47 MB.

sudo apt-get install texlive-lang-cjk --no-install-recommends

**Comment by josuetex** [comment]
Resolvido com essa última instalação. Obrigado @Ronair .

**Comment by mateusnava** [comment]
@josuetex e @Ronair valeu!

Funcionou perfeitamente instalando o texlive-lang-cjk. (sudo apt-get install texlive-lang-cjk --no-install-recommends)
