### ISSUE TITLE
Linha digitável

### ISSUE THREAD

**Issue by emaiax** [kivanio/brcobranca#88]
Utilizando a gem, percebi que não consigo o código da linha digitável do boleto.

O que acham de implementar?

**Comment by emaiax** [comment]
Já está implementado em `brcobranca/lib/brcobranca/formatacao.rb`, desculpem.

**Comment by kivanio** [comment]
Só chamar: boleto.codigo_barras.linha_digitavel

**Comment by emaiax** [comment]
Obrigado @kivanio :+1:
