### ISSUE TITLE
CNAB400 Bradesco

### ISSUE THREAD

**Issue by efmiglioranza** [kivanio/brcobranca#92]
Pela documentação que tenho aqui, o Bradesco utiliza algumas posições diferentes no arquivo de retorno CNAB400. Mais alguém tem esse problema ou estou com a documentação errada?

**Comment by efmiglioranza** [comment]
Por exemplo, o que mais tá me atrapalhando agora:

Bradesco:
063 a 070 Zeros
071 a 082 (*) Identificação do Título no Banco

Itau:
063 a 070 NOSSO NÚMERO IDENTIFICAÇÃO DO TÍTULO NO BANCO
071 a 082 BRANCOS

Pelo jeito é necessário separar as implementações do retorno também por banco, como é feito nas remessas e nos boletos.

**Comment by kivanio** [comment]
@efmiglioranza você diz remessa ou retorno? Pelo título está ambíguo.

Sim, o retorno e remessa são layouts diferentes.
Eu nunca quis colocar isso na gem, o retorno que está é antigo e foi pra um caso específico.
A todos que me perguntam eu respondo sempre a mesma coisa, que recomendo a gem do Eduardo https://github.com/eduardordm/cnab240

Agora, se você quiser investir um tempo e produzir esse código de retorno aqui,
fique a vontade, terei o maior prazer em fazer o merge e dar os créditos ;)

**Comment by efmiglioranza** [comment]
@kivanio o retorno mesmo, achei que todos os bancos seguiam o mesmo layout, mas não é o caso. Vou dar uma olhada na gem do Eduardo então, creio que o 240 também sirva, se não eu implemento o 400. Abraço!
