### ISSUE TITLE
Retorno de linha nos arquivos de Remessa

### ISSUE THREAD

**Issue by efmiglioranza** [kivanio/brcobranca#98]
O Bradesco utiliza quebra de linha com retorno (\r\n) ao final de cada registro. Existem alguns testes verificando o tamanho dos registros das Remessas que estão falhando se isso for alterado. Alguém sabe se isso é válido ou ignorado por outros bancos também?

**Comment by kivanio** [comment]
Todos devem ter a quebra.

**Comment by efmiglioranza** [comment]
@kivanio blz, mas é só a quebra (\n) ou quebra com retorno (\r\n)? O Bradesco não reconhece apenas \n, só com \r\n. Isso é válido para todos?

**Comment by kivanio** [comment]
Que eu saiba, todos quebram com \r\n.
Mas cada banco é uma porcaria pra validar :)
Só enviando no sistema do banco pra saber qual é a real.
Até porque muitas vezes a documentação não reflete a realidade.
