### ISSUE TITLE
Boleto Unicred

### ISSUE THREAD

**Issue by Gubio** [kivanio/brcobranca#99]
Bom dia amigos, gostaria de saber como eu posso contribuir para a criação do boleto para Unicred?
é bem parecido com o sicoob.

http://api.ning.com/files/YhwQqZhqiBaEhvZsSdHj43WcNmsgbaQdmV5qSKBTxRuTkJD-zOKtDfboRr8NCn20yxUi*PYL3NMVPItG3Y*XpgR3PcnaNlG0/COBRANCAUNICREDTROCAELETRONICACEDENTECNAB240E400ATUALIZADO.pdf

**Comment by kivanio** [comment]
@Gubio Se for realmente parecido, basta clonar o arquivo do Sicoob e trabalhar em cima do que for diferente entre os dois.
O ideal é ter um boleto da Unicred em mãos, assim você usa os mesmos dados para testar e gerar um boleto igual ao que você já tem.

É bem simples de fazer ;)

**Comment by Gubio** [comment]
mas não seria interessante atender o unicred tbm?

**Comment by marceloboth** [comment]
@Gubio você implementou esse boleto? Estou precisando dele, caso você ainda não tenha, vou implementar.

**Comment by Gubio** [comment]
Eu fiz e foi homologado. mas não criei o TDD. está no meu perfil o fork.

**Comment by marceloboth** [comment]
:+1:  Eu crio os testes. Vou ver o seu fork.

**Comment by Gubio** [comment]
basicamente é TUDO igual ao bradesco, o que muda é o Nosso numero.

**Comment by Gubio** [comment]
def boletos_teste
		@todos_boletos = []
		@conta_bancaria = DadoBancario.find(params[:id])

		@conta_bancaria.quantidade_hologacao.times do |i|

			boleto_banco

			@documento.cedente            = @conta_bancaria.nome_cedente
			@documento.documento_cedente  = @conta_bancaria.cnpj_cedente
			@documento.agencia            = @conta_bancaria.agencia
			@documento.conta_corrente     = @conta_bancaria.conta
			@documento.convenio			  = @conta_bancaria.convenio
			@documento.valor              = 1
			@documento.sacado             = "Federação das Assóciações Empresariais de Santa Catarina"
			@documento.sacado_documento   = "78354636000129"
			@documento.numero_documento   = @conta_bancaria.nosso_numero.to_i + (i+1)
			if @conta_bancaria.byte_idt.present?
				@documento.byte_idt       	= @conta_bancaria.byte_idt
		 	end
		 	if @conta_bancaria.posto.present?
				@documento.posto        		= @conta_bancaria.posto
			end
			@documento.data_documento 	  = Date.today	
			@documento.dias_vencimento 	  = Date.today + 10 - Date.today
			@documento.avalista 		  = @conta_bancaria.avalista 
			@documento.avalista_documento = @conta_bancaria.avalista_documento 
			@documento.cedente_endereco   = @conta_bancaria.cedente_endereco  
			@documento.avalista_endereco  = @conta_bancaria.avalista_endereco 
			@documento.instrucao1         = @conta_bancaria.instrucao1
			@documento.instrucao2         = @conta_bancaria.instrucao2
			@documento.instrucao3         = @conta_bancaria.instrucao3
			@documento.instrucao4         = @conta_bancaria.instrucao4
			@documento.instrucao5         = @conta_bancaria.instrucao5
			@documento.instrucao6         = @conta_bancaria.instrucao6
			@todos_boletos << @documento
		end

	send_data Brcobranca::Boleto::Base.lote(@todos_boletos), :filename => "homologacao.#{@conta_bancaria.banco.nome}.#{Time.now}.pdf"
end



Se você fizer algo assim, já vai funcionar.

**Comment by marceloboth** [comment]
Bradesco? Achei que era do Sicredi, pelo que você falou no primeiro comentário, devido ao nome do banco e pelo `@conta_bancaria.byte_idt.present?` nesse seu código.

**Comment by Gubio** [comment]
eu montei isso para facilitar a homologação com o banco. funciona para todos os bancos que uso.
sim é bradesco

**Comment by marceloboth** [comment]
Esse boleto foi adicionado ao Brcobranca, com base Sicredi, estou fechando a issue.
